### ISSUE TITLE
支持混淆com.android.library方式打包出aar包？

### ISSUE THREAD

**Issue by SeanCode** [shwenzhang/AndResGuard#102]
你好，是不是可以考虑支持一下在打aar包的时候混淆呢？

**Comment by simpleton** [comment]
@SeanCode 这个我感觉没有办法支持，因为混淆过程涉及修改最后打包生成的resource.asrc文件。这个原理和proguard还是有比较大的区别的。
@shwenzhang 你有什么想法？

**Comment by SeanCode** [comment]
build目录下有aar的所有资源和class  是不是可以扫描一遍 然后修改  直接把build下面的修改完了 生成resource.asrc那一步就可以不用管了

**Comment by simpleton** [comment]
@SeanCode 这个工具在设计的时候没有切入编译过程，输入、输出都是apk文件。

**Comment by hakulatata** [comment]
也遇见这个问题！在没有混淆的时候还可以看见class.jar的文件，混淆后毛都没有，各种-keep 也没用，是不是不支持这种做法？

**Comment by simpleton** [comment]
@hakulatata 这个工具只和资源相关，和class无关的。
