### ISSUE TITLE
gif 压缩后不能正常显示，有人遇到这个问题吗？

### ISSUE THREAD

**Issue by thomaszheng** [shwenzhang/AndResGuard#105]

**Comment by simpleton** [comment]
不是很了解你load gif使用的方法。可否提供相关load fail的log或者callstack.

**Comment by thomaszheng** [comment]
在布局文件中设置的，load_icon就是一张gif的图片，无法显示。

         <pl.droidsonroids.gif.GifImageView
            android:layout_width="@dimen/dp100"
            android:layout_height="@dimen/dp100"
            android:src="@mipmap/load_icon"
            android:layout_centerInParent="true" />

**Comment by simpleton** [comment]
我个人在项目是使用glide加载gif是没有问题的，不是很清楚`GifImageView`这个控件加载的方法。这里可以单独为其增加白名单，让其强制不混淆。

**Comment by likangyan88** [comment]
最近我也碰到了，把gif加入白名单强制不混淆，仍然不行。

**Comment by simpleton** [comment]
如果你使用了路径加载，请参照如下说明：
https://github.com/shwenzhang/AndResGuard/blob/master/README.zh-cn.md#%E7%99%BD%E5%90%8D%E5%8D%95

**Comment by likangyan88** [comment]
试了两个步骤，发现gif动画仍然动不了。
1、keepRoot = true；keep住所有资源原始路径。
2、whiteList = ["R.drawable.gif_icon"]；把gif动画资源加入白名单。
另外，后来把apk反编译后看到gif_icon路径和路径都是不被混淆的，但是gif动画仍然不行。如果不用andResguard的话，一切正常，奇怪。

**Comment by simpleton** [comment]
@likangyan88 `use7zip = false` 试试？

**Comment by likangyan88** [comment]
也不行
