### ISSUE TITLE
我这配置build.gradle遇到一个错误.已经参考了AndResGuard-example项目的配置了

### ISSUE THREAD

**Issue by yaodiwei** [shwenzhang/AndResGuard#109]
Gradle 'MyTestProject' project refresh failed
Error:Index: 0, Size: 0

研究了大半天,来来回回检查了很多遍,还是没找出问题.
有遇到同样错误的人吗?

**Comment by anenn** [comment]
贴出你的配置文件，否则不知道你怎么配的

**Comment by simpleton** [comment]
@yaodiwei 可否尝试使用 classpath ('com.tencent.mm:AndResGuard-gradle-plugin:1.1.14') { changing = true } 引入AndResGuard？

PS:下次提issue时可以使用--stacktrace的log。

**Comment by yaodiwei** [comment]
@simpleton 
加了这句就变好了.
真的是万分感谢!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
好人一生平安!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
感谢感谢!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
