### ISSUE TITLE
po主，和Tinker怎么配合？？

### ISSUE THREAD

**Issue by vihuela** [shwenzhang/AndResGuard#113]
tinker执行是设置oldApk，oldApk的R文件，然后命令行生产差异文件，
怎么指定生成差异文件是经过resguard的。。。。就是这个问题

**Comment by simpleton** [comment]
可以指定mappingFile为oldApk生成的resource_mapping，这个文件会生成在和混淆apk相同的目录下。

**Comment by vihuela** [comment]
明白po主的意思，这里我实践有一个疑问：
v1.0apk
gradlew resguardRelease执行的apk、mapping假设为A、B
gradlew tinkerPatchRelease执行的apk、mapping、r文件假设为A1、B1，C1

v2.0apk
gradlew resguardRelease执行的apk、mapping假设为A+、B+
gradlew tinkerPatchRelease执行的apk、mapping、r文件假设为A1+、B1+，C1+

我现在是在v2.0环境下生成与v1.0差异包：oldApk为A，oldMapping为B，oldR为C1，
前后好像不一致。po主意思是，仅仅把oldMapping修改为resguard之后的mapping就行了么？？

**Comment by simpleton** [comment]
#ref https://github.com/Tencent/tinker/issues/63
#ref [Use AndResGuard In TinKer](https://github.com/Tencent/tinker/wiki/Tinker-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%AF%8F%E6%AC%A1%E7%BC%96%E8%AF%91%E6%88%91%E5%BA%94%E8%AF%A5%E4%BF%9D%E7%95%99%E5%93%AA%E4%BA%9B%E6%96%87%E4%BB%B6%E5%A6%82%E4%BD%95%E5%85%BC%E5%AE%B9andresguard)
Tinker的相关issue里有讨论，可以参照上面2个连接。
PS: 不太理解你的不一致是哪里不一致呢？
