### ISSUE TITLE
Error:Execution failed for task ':app:resguardRelease'. > can't the get signConfig for release build

### ISSUE THREAD

**Issue by xiangxm** [shwenzhang/AndResGuard#116]
请问使用gradlew resguardRelease会报错
Error:Execution failed for task ':app:resguardRelease'.
> can't the get signConfig for release build

**Comment by simpleton** [comment]
如果使用buildType = release的话，需要配置signConfig信息。

**Comment by GitACDreamer** [comment]
@simpleton  配置了signConfig   release 和 debug都配置了，为什么还会报这个错误，我的证书是android studio 生成的.jks格式，而你的demo里面是.keystore 格式的是不是这个原因？

**Comment by simpleton** [comment]
@GitACDreamer 可以提供一个可以复现问题的测试证书？另外确认下你使用的是v1 还是 v2签名。

**Comment by simpleton** [comment]
fixed in 1.2.3

**Comment by GitACDreamer** [comment]
@simpleton 谢谢问题已经解决了，是我自己没配置正确

**Comment by GitACDreamer** [comment]
@simpleton 谢谢！问题已经解决了，是我自己没配置正确

**Comment by AImiracle** [comment]
你咋解决的？？？

**Comment by GitACDreamer** [comment]
@AImiracle 我已经看到你的邮件了，我把我以前做的那个APP的 build.gradle配置文件发送邮箱给你，当时是我的签名文件更改了位置，路径发生变化，根据作者的document 来操作应该是没问题的。

**Comment by GitACDreamer** [comment]
1. 配置证书的路径和账号、密码要正确
2. 在build.gradle文件中配置正确就好了，详细配置看此文件


--


Best regards,

Leland
广东省深圳市南山区蛇口街道沿山路23号胜发大厦A座3楼
18588254125

在 2018-01-24 14:45:13，"AImiracle" <notifications@github.com> 写道：


你咋解决的？？？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
res path mapping:
    res/mipmap-hdpi-v4 -> res/mipmap-hdpi-v4
    res/mipmap-mdpi-v4 -> res/mipmap-mdpi-v4
    res/mipmap-xhdpi-v4 -> res/mipmap-xhdpi-v4
    res/mipmap-xxhdpi-v4 -> res/mipmap-xxhdpi-v4
    res/mipmap-xxxhdpi-v4 -> res/mipmap-xxxhdpi-v4

**Comment by GitACDreamer** [comment]
@AImiracle 尴尬，邮箱里面回复的，github上也会显示啊，暴露了我的手机和一些相关信息o(╥﹏╥)o，其中两个附件和一张图片我已经发送给你了。  就是跟着demo来就不会错，主要是细心，祝你好运(*￣︶￣)
