### ISSUE TITLE
出现多包，但只想要一包

### ISSUE THREAD

**Issue by Saqrag** [shwenzhang/AndResGuard#118]
app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_signed.apk
app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_signed_7zip.apk
app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_signed_7zip_aligned.apk
app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_signed_aligned.apk
app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_unsigned.apk

打包完出现这五种包，但我只想要一种Boman_v1.0.0_baidu_signed_7zip_aligned.apk包，怎么弄呀，我用的指令为gradlew resguardBaiduRealease  多谢

**Comment by simpleton** [comment]
用这个`app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_signed_7zip_aligned.apk`。

一般都使用`*.signed_7zip_aligned.apk`

**Comment by Saqrag** [comment]
我只想打包app/build/outputs/apk/AndResGuard_Boman_v1.0.0_baidu/Boman_v1.0.0_baidu_signed_7zip_aligned.apk这个包，其它包不想打，能这样打包吗？ 多谢

**Comment by simpleton** [comment]
其他包是打最终包的依赖路径，不会造成额外的开销。后续版本会考虑删除无用的中间路径包。

**Comment by Saqrag** [comment]
再次感谢，知道了

**Comment by HDHunter** [comment]
thank you all the same.

**Comment by DysaniazzZ** [comment]
所以如何配置才能删除中间的路径包呢，我只需要最后的结果包就可以了。@simpleton
