### ISSUE TITLE
同时使用anim与animator资源，只将anim加入白名单，资源压缩失败

### ISSUE THREAD

**Issue by zxdtang** [shwenzhang/AndResGuard#119]
app中同时使用了anim与animator资源文件。anim加入了白名单，animator未加入。资源压缩过程中，会出现indexOutofBounds的错误。看代码是计算资源数量时有错误。目前的workaround是将animator也加入白名单。

**Comment by simpleton** [comment]
麻烦提供一下错误的log，和你使用的版本。多谢

**Comment by zxdtang** [comment]
![log](https://cloud.githubusercontent.com/assets/9458739/21559284/5ac7251e-ce84-11e6-8037-bdda09aee499.png)，使用版本1.1.4，用gitlab上daima run起来也一样

**Comment by simpleton** [comment]
你更新一下试试？你这个版本略微有点旧了，最新版是1.1.16

**Comment by simpleton** [comment]
Please reopen it when there is the same issue in version 1.1.16
