### ISSUE TITLE
7zip 到底压缩了什么内容

### ISSUE THREAD

**Issue by googleapivalid** [shwenzhang/AndResGuard#122]
Repackage with 7zip.  这句话的意思是工具压缩了什么内容呢？

> resources.arsc 在 APK 安装之后仍需要被频繁的读取，如果将它进行压缩，在每次读取前系统都必须进行解压的操作，从性能上考量这显然是得不偿失的。所以，赶紧摒弃通过压缩 resources.arsc 来给 APK 瘦身的方法吧。

目前这个工具只是说类似proguard通过缩短文件路径，名称之类的减小size的对不对？ 没有压缩resources.arsc吧？

**Comment by simpleton** [comment]
可以配置，按readme的配置是会压缩的

**Comment by simpleton** [comment]
@googleapivalid 
```
compressFilePattern = [
        "*.png",
        "*.jpg",
        "*.jpeg",
        "*.gif",
        "resources.arsc"
    ]
```
相关配置在这里。

你引用这段话我曾经在closed的issue中解释过，#84。对运行时的性能影响不大。

**Comment by googleapivalid** [comment]
好的，谢谢～
