### ISSUE TITLE
集成易联支付崩溃

### ISSUE THREAD

**Issue by shuiyouwen** [shwenzhang/AndResGuard#123]
本来资源混淆是完全没有问题的，当我集成易联的支付后再去资源混淆就会崩溃。
下图是易联支付引用资源文件
![image](https://cloud.githubusercontent.com/assets/12215733/21980953/3bbbde2c-dc20-11e6-8619-5fbc72c5e891.png)
下面是我写的白名单：
  whiteList = [
            //易联
            "R.drawable.payeco*",
            "R.layout.payeco*",
            "R.dimen.payeco*",
            "R.color.payeco*",
            "R.string.app_name",
            "R.string.payeco*",
            "R.style.payeco*",
            "R.layout.activity_result",
    ]
谁能拯救我这个无知的小白。。

**Comment by simpleton** [comment]
@shuiyouwen 可否贴一些crash stack，或者发我apk包，我debug下。 sunsj1231[at]gmail.com

**Comment by shuiyouwen** [comment]
已给你发了邮件，麻烦有时间看看~

**Comment by shuiyouwen** [comment]
邮件被拦截了。。所以在这发个附件吧~
附件中是可以复现的demo，资源混淆后点击提交按钮就可以复现问题了。
[demo2.zip](https://github.com/shwenzhang/AndResGuard/files/710259/demo2.zip)

**Comment by shuiyouwen** [comment]
解决了。哈哈，打扰了  不好意思。。

**Comment by simpleton** [comment]
没关系，也没帮上什么。crash大体就是这个sdk使用了绝对路径，或者使用了`getIdentifier `去获取资源，加入白名单就OK了。
