### ISSUE TITLE
Apk after 7zip call AssetManager#list(String path) !

### ISSUE THREAD

**Issue by PykeChen** [shwenzhang/AndResGuard#125]
包经过资源混淆后，跑xxx_signed_7zip_aligned，经过调试发现在AssetManager#list(String path) 调用后得到一个string arrary的数组，但是数组index为0的位置得到的竟然是一个空字符，日志
"doCopyMaterials ~~~ name :"，对比xxx_signed_aligned的包则没有这个问题，想问下这个怎么解决，虽然可以做兼容判断，但是还是很奇怪。使用 7-Zip 16.04版本，想问下是否遇到过，使用什么版本的7-zip或者什么方法能解决?

**Comment by PykeChen** [comment]
另外想问下，如何结合渠道打包，进行配置呢？需要将andResGuard 命令放到哪进行配置?

**Comment by simpleton** [comment]
@PykeChen 
1. 7zip可以使用我们gralde的配置
2. 关于渠道包，可以在AndResGuard之后来打渠道包。因为大家使用的打渠道包工具不同，所以无法具体指出要如何操作，但只要把渠道包的输入apk配置成AndResGuard输出的apk即可。
