### ISSUE TITLE
可不可以支持v2模式的签名

### ISSUE THREAD

**Issue by jonyChina162** [shwenzhang/AndResGuard#127]
通过该插件打出来的包使用的是jarsigner做的签名，而在android7上会验证v2模式的签名包，问下这个插件可不可以生成包后用apksigner进行签名

**Comment by simpleton** [comment]
@jonyChina162
暂时还不支持, 下个版本会支持.
ref #115

**Comment by 401885064** [comment]
问了美团那边的Walle是否支持AndResGuard   得到的答复 希望参考下 经济等待下个版本        [能和AndResGuard结合使用吗？](https://github.com/Meituan-Dianping/walle/issues/76#issuecomment-285300046)

**Comment by simpleton** [comment]
@401885064 你可以先disable掉7zip压缩，然后再用walle-cli尝试下签名和多渠道。
```gradle
andResGuard {
    use7zip = false
}
```

正在开发的支持v2签名，也会disable掉7zip。因为7zip我引的是bin，短时间不会做7zip的v2签名支持

**Comment by jonyChina162** [comment]
@401885064 我自己参考了AndResGuard的源码，把他内部的签名模式改成了v2模式，然后对打出的母包使用walle打多渠道，是否需要参考，要参考的话我可以把代码上传到我的github，不过7zip是确定用不了了

**Comment by simpleton** [comment]
也欢迎PR

**Comment by 401885064** [comment]
@jonyChina162    谢谢，暂时不需要 ！  欢迎PR  哈哈哈
