### ISSUE TITLE
无法混淆，运行后没有生成APK

### ISSUE THREAD

**Issue by longtaoge** [shwenzhang/AndResGuard#13]
shwenZhang 你好，
感谢你的资源混淆工具
刚才我试了一下，在AndroidStudio 控制台运行项目 ，没有出现预期的 7个APK，只是出现了两个资源包，一个是混淆过的，一个是没有混淆过的，我看了一下，还是没有找到原因，不知道这是哪的问题？
https://github.com/longtaoge/DevelopmentNotes/blob/master/image/3A02.tmp.png
![](https://github.com/longtaoge/DevelopmentNotes/blob/master/image/3A02.tmp.png)

**Comment by shwenzhang** [comment]
图片看不见，是不是没有输入签名信息？如果没输入签名信息，或者签名信息不对，的确只有两个文件

**Comment by longtaoge** [comment]
windows 环境下   混淆了个简单APK 可以正常生成两个APK，直接混淆项目APK后，仍然是只有资源文件，没有生成预期的APK

**Comment by shwenzhang** [comment]
能把安装包发到shaowenzhang1986@gmail.com吗？

**Comment by shwenzhang** [comment]
@longtaoge ，你这个安装包是怎么编译出来的？value文件夹应该不会存在的，它们会编到resources.arsc中

**Comment by longtaoge** [comment]
我是用eclipse 正常编译的

同样的方法打包的两个测试APK没有问题



61852263@qq.com
 
发件人： shwenzhang
发送时间： 2015-10-20 11:26
收件人： shwenzhang/AndResGuard
抄送： longtaoger
主题： Re: [AndResGuard] 无法混淆，运行后没有生成APK (#13)
@longtaoge ，你这个安装包是怎么编译出来的？value文件夹应该不会存在的，它们会编到resources.arsc中

**Comment by shwenzhang** [comment]
release版本不会出现这个问题
