### ISSUE TITLE
勘误? ResourceApkBuilder.addStoredFileIn7Zip(...) 中调用7za命令

### ISSUE THREAD

**Issue by zhEdward** [shwenzhang/AndResGuard#130]
jar  version : 1.1.16

在注释的位置表明是 **"极限压缩"** ( `-mx0` ) 我查阅[说明手册](https://sevenzip.osdn.jp/chm/cmdline/switches/method.htm)说的是，数字越大压缩越高（也就是 `-mx9`）
我在cygwin中实测 也是 9 压缩的体积更小点。

**Comment by simpleton** [comment]
有部分文件是不能压缩的，StoredFile都是已-mx0已不压缩的方式。
