### ISSUE TITLE
怎么在白名单里添加配置，让res下的某个文件夹名不被混淆

### ISSUE THREAD

**Issue by shizhangbiao** [shwenzhang/AndResGuard#132]
怎么在白名单里添加配置，让res下的某个文件夹名不被混淆
比如我想让drawable这个文件夹不被重命名
比如这句  res/drawable -> r/f该怎么处理

**Comment by simpleton** [comment]
配置成`res/drawable -> res/drawable`即可。

**Comment by shizhangbiao** [comment]
我是想配置成res/drawable -> res/drawable
关键在whiteList里怎么添加配置

**Comment by simpleton** [comment]
@shizhangbiao whiteList和mapping是2个维度的白名单配置，whiteList只能保证名字不会混淆，而mapping是保证路径的，你可以copy生成的mapping，做为参数传入
```gradle
andResGuard {
    mappingFile = file("./resource_mapping.txt")
}
```

**Comment by shizhangbiao** [comment]
好的，晓得了，谢谢
