### ISSUE TITLE
Could not find com.tencent.mm:v2sign:1.2.0

### ISSUE THREAD

**Issue by qinly** [shwenzhang/AndResGuard#134]
* What went wrong:
A problem occurred configuring root project '***'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.tencent.mm:v2sign:1.2.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/tencent/mm/v2sign/1.2.0/v2sign-1.2.0.pom
         https://jcenter.bintray.com/com/tencent/mm/v2sign/1.2.0/v2sign-1.2.0.jar
     Required by:
         project : > com.tencent.mm:AndResGuard-gradle-plugin:1.2.0 > com.tencent.mm:AndResGuard-core:1.2.0

**Comment by simpleton** [comment]
Sorry for that, plz use the last working version 1.1.16 now. I'll fix it
asap

**Comment by simpleton** [comment]
@qinly It should work now.  please run `./gradlew --refresh-dependencies` for making cache invalid.
Feel free to reopen issue when it doesn't work.

**Comment by devwangxiaogang** [comment]
A problem occurred configuring project ':****'.
> Could not resolve all dependencies for configuration ':****:classpath'.
   > Could not find com.tencent.mm:AndResGuard-gradle-plugin:1.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.pom
         https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.jar
     Required by:
         project :****

It still can't work.
