### ISSUE TITLE
AndResGuard-gradle-plugin:1.1.13升级成1.1.16以后，packer-ng-plugin以前集成的多渠道打包失效的问题

### ISSUE THREAD

**Issue by 18511084155** [shwenzhang/AndResGuard#135]
集成多渠道打包问题：
project.afterEvaluate {
    //在Release后执行资源混淆，然后多渠道打包
    //打包命令 ./gradlew resguard  或者 gradle clean resguard
    tasks.getByName("resguard") {
        it.doLast {
            println 'channel package task begin'
            def oldName= "new_v${versions.version_name}"
            def fileName = oldName + "_signed_7zip_aligned.apk"
            def rApk = new File("app/build/outputs/apk/AndResGuard_" + oldName+ "/" + fileName)
            if (rApk.exists()) {
                println 'resGuard apk exits begin channel package'
                packageChannel(rApk.absolutePath)

            }
        }
    }
}
提示找不到：resguard任务？
查看了你插件的源码发现你的任务这块改变比较大，没法满足以前的构建方式了。
询问下作者，你能不能在执行AndResGuard任务以后，提供一个任务作为扩展方式，提供一个调用packer-ng-plugin多渠道打包的一个入口？

**Comment by simpleton** [comment]
现在的命名规则和android构建assemble保持了一致。规则是resguard[FlavorName][BuildType]。你可以基于这个修改。 后续会考虑对packer-ng或者walle的更好支持。 但感觉gradle脚本也很容易把2个插件应用在一起，不过还是对使用者不太友好。
