### ISSUE TITLE
Failure [Invalid apk]

### ISSUE THREAD

**Issue by TCGOGOGO** [shwenzhang/AndResGuard#137]
Hi，执行命令java -jar AndResGuard-cli-1.1.16.jar xxx.apk后，adb install时提示
Failure [Invalid apk]，解压重打包的方式是什么样的？[注：混淆前的apk可以正常安装]

**Comment by simpleton** [comment]
有更多报错信息么？ 不过jar得方式后续会慢慢不再维护，推荐使用gradle的方式集成。

**Comment by simpleton** [comment]
@TCGOGOGO 我这里先关闭了，如果有更多信息，您可以重新打开。
