### ISSUE TITLE
AndResGuard配置好之后，能否配置到Run/Debug Configurations中，直接运行安装资源混淆之后的APK

### ISSUE THREAD

**Issue by fengqingxiuyi** [shwenzhang/AndResGuard#140]
AndResGuard配置好之后，能否配置到Run/Debug Configurations中，直接运行安装资源混淆之后的APK

**Comment by simpleton** [comment]
@fengqingxiuyi 你可以直接修改Run的configuartions为AndResGuard的相关task，但是一般不推荐。因为和instant run等相关debug的插件，我这边没有做适配。

**Comment by fengqingxiuyi** [comment]
哦，好的
