### ISSUE TITLE
resources-debug-stripped.ap_ specified for property 'resourceFile' does not exist

### ISSUE THREAD

**Issue by fengqingxiuyi** [shwenzhang/AndResGuard#142]
![image](https://cloud.githubusercontent.com/assets/20492527/24101508/8e7c4b00-0db3-11e7-9fa5-2fb771fca30a.png)

**Comment by simpleton** [comment]
这个是在什么情况下出现的呢？

**Comment by fengqingxiuyi** [comment]
在gradle中配置了资源混淆内容后，使用./gradlew resguardDebug打包会报这样的错，不过我前天这样打包的时候还没有问题，不知道是我的锅还是你升级之后的锅

**Comment by fengqingxiuyi** [comment]
问题已经解决，但是根本原因还不清楚，目前发现如果打包命令是./gradlew resguardRelease的话是没有问题的，但是如果打包命令是./gradlew resguardDebug的话，需要将shrinkResources设置为false才可以，如果你清楚更根本原因的话，请告知

**Comment by simpleton** [comment]
@fengqingxiuyi 这个应该不是AndResGuard引入的问题，https://developer.android.com/studio/build/shrink-code.html#shrink-resources
