### ISSUE TITLE
gradle中配置打包没有7zip包

### ISSUE THREAD

**Issue by fengqingxiuyi** [shwenzhang/AndResGuard#143]
![image](https://cloud.githubusercontent.com/assets/20492527/24130664/f43e912a-0e24-11e7-843a-25343a89f117.png)
只有这三个了，打包命令：./gradlew resguardRelease
参数配置：
apply plugin: 'AndResGuard'

andResGuard {
    mappingFile = null
    use7zip = true
    useSign = true
    // 打开这个开关，会keep住所有资源的原始路径，只混淆资源的名字
    keepRoot = false
    whiteList = [
            // for your icon
            "R.drawable.ic_launcher",
            // for umeng update
            "R.string.umeng*",
            "R.string.UM*",
            "R.string.tb_*",
            "R.layout.umeng*",
            "R.layout.tb_*",
            "R.drawable.umeng*",
            "R.drawable.tb_*",
            "R.anim.umeng*",
            "R.color.umeng*",
            "R.color.tb_*",
            "R.style.*UM*",
            "R.style.umeng*",
            "R.id.umeng*"
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
            "resources.arsc"
    ]
    sevenzip {
        artifact = 'com.tencent.mm:SevenZip:1.2.0'
        path = "/usr/local/bin/7za"
    }
}

**Comment by fengqingxiuyi** [comment]
将版本号改为1.1.16就可以了

**Comment by simpleton** [comment]
@fengqingxiuyi 如果使用了V2签名，暂时无法进行7zip压缩。如果你对安装包的大小特别关注，可以在signingConfigs中使用v2SigningEnabled false 来关闭v2签名。1.1.16不支持v2签名。
duplicated #139
