### ISSUE TITLE
Android Studio 中 1.2.0版本在混淆打包后 没有7zip压缩包 怎么回事呢？1.1.16版有7zip包

### ISSUE THREAD

**Issue by yxyhail** [shwenzhang/AndResGuard#146]
Android Studio 中 1.2.0版本在混淆打包后 没有7zip压缩包 怎么回事呢？1.1.16版有7zip包

**Comment by imknown** [comment]
https://github.com/shwenzhang/AndResGuard#with-gradle
是这么写的吗?

**Comment by yxyhail** [comment]
对啊 就是照上边写的  我用的是Android Studio 2.3 
 classpath 'com.android.tools.build:gradle:2.3.0'
distributionUrl  gradle-3.3-all.zip

AndResGuard starting...
unziping apk to E:\SDK_Weibo\weibo_android_sdkmaster\weibosdkdemo\app\build\outputs\apk\AndResGuard_app-release\temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename com.sina.weibo.sdk.demo
resources mapping file E:\SDK_Weibo\weibo_android_sdk-master\weibosdkdemo\app\build\outputs\apk\AndResGuard_app-release\resource_mapping_app-release.txt 
done writing new resources.arsc 
resources.arsc Character Encoding: utf-8
general unsigned apk: app-release_unsigned.apk
DestResDir 403 rawResDir 403
zipaligning apk: app-release_unsigned.apk
signing apk: app-release_aligned_signed.apk
AndResGuard done, you can go to file to find the output E:\SDK_Weibo\weibo_android_sdk-master\weibosdkdemo\app\build\outputs\apk\AndResGuard_app-release

BUILD SUCCESSFUL

Total time: 6.909 secs

**Comment by imknown** [comment]
看了一下输出, 确实和你一样.

**Comment by yxyhail** [comment]
: )

**Comment by weinierfei** [comment]
1.2.0版本默认开启了v2签名,7z关闭

**Comment by yxyhail** [comment]
哦哦

**Comment by simpleton** [comment]
@yxyhail 你可以通过 v2SigningEnabled false 来关闭v2签名，使得可以使用7zip压缩。
