### ISSUE TITLE
Error:Cause: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by quelang9** [shwenzhang/AndResGuard#147]
按照文档集成的时候报错

**Comment by simpleton** [comment]
@quelang9 请确认是否是AndResGuard引入的问题。
https://www.google.com.tw/?gws_rd=ssl#q=unable+to+find+valid+certification+path+to+requested+target+android&*

**Comment by simpleton** [comment]
@quelang9 确认是AndResGuard引入的问题，欢迎重新打开issue。
