### ISSUE TITLE
Gradle 插件报错 

### ISSUE THREAD

**Issue by weixinfree** [shwenzhang/AndResGuard#149]
Error:Execution failed for task ':app:resguardRelease'.
> Could not get unknown property 'v2SigningEnabled' for SigningConfig_Decorated{name=release, storeFile=XXX.keystore, storePassword=XXX, keyAlias=XXX, keyPassword=XXX, storeType=XXX.keystore} of type com.android.build.gradle.internal.dsl.SigningConfig.

Android Studio 版本2.3 
gradle版本 2.14.1

**Comment by simpleton** [comment]
@weixinfree 麻烦把把版本号更新到1.2.1，尝试下还是否有这个问题。

**Comment by weixinfree** [comment]
可以了，多谢作者😊
