### ISSUE TITLE
混淆完毕，旧资源还在包里

### ISSUE THREAD

**Issue by wszf** [shwenzhang/AndResGuard#15]
RT
确实多了R文件夹，但是未混淆资源还在生成的包内，并且已签名，是我姿势不对吗？

**Comment by wszf** [comment]
改了下源码，粗略的将原始资源剔除了

**Comment by shwenzhang** [comment]
能把安装包发我一下？shaowenzhang1986@gmail.com

**Comment by wszf** [comment]
这个和包有关系吗？我测试了几个app都是混淆完成后原有的资源还在包内

**Comment by shwenzhang** [comment]
资源当然会在，只是改了文件名而已。

2015-10-20 13:06 GMT+08:00 wszf <notifications@github.com>:

**Comment by wszf** [comment]
我的意思是包内同时存在两份资源，一个是改过名字的，另外一份就是正常未改名字的。虽然生成包已经使用了改过名字的资源，但是并未删除未改名字的资源，是这样把？
