### ISSUE TITLE
不太理解这句：“compress参数对混淆效果的影响 若指定compess 参数.png、.gif以及*.jpg，resources.arsc会大大减少安装包体积。若要支持2.2，resources.arsc需保证压缩前小于1M。”

### ISSUE THREAD

**Issue by Aarontaken** [shwenzhang/AndResGuard#150]
请问“若要支持2.2，resources.arsc需保证压缩前小于1M”是什么意思啊，我是用gradle插件的形式集成的，2.2是指什么？

**Comment by simpleton** [comment]
@Aarontaken 这个2.2只指的sdk version。。。已经是很古老的版本了

**Comment by Aarontaken** [comment]
额 好吧，其实还有个问题哈，下面是我资源混淆和压缩apk后的结果，资源混淆后减少了2.8M，资源混淆+7zip资源压缩减少了3.3M，7zip资源压缩只有0.5M的贡献吗？如果是这样，资源名混淆减小了2.8M空间，我理解的是resources.arsc文件因存储文件路径而减少了2.8M，可我发现resources.arsc并没有那么大（2.5M），显然不对，那减少的是什么空间呢？

![image](https://cloud.githubusercontent.com/assets/20335015/24793795/f2830a70-1bb5-11e7-84cb-08345f2b91b3.png)

**Comment by simpleton** [comment]
@Aarontaken  嗯，0.5M其实挺多的了，7zip比zip压缩率高也只是因为字典的原因。另外2.8M其实大部分是资源在压缩包的存储方式，我会改成Deflated。短路径一般只能压缩几百K，当然这个根据每个APP的情况不同也有差异。

**Comment by Aarontaken** [comment]
@simpleton 嗯 我明白了！ 非常感谢！
