### ISSUE TITLE
使用 AndResGuard-cli-1.2.0.jar 不开启7zip ， 压缩过后 V2 签名降级成为了 V1 的签名

### ISSUE THREAD

**Issue by Jimmy-J** [shwenzhang/AndResGuard#154]
使用 CheckAndroidV2Signature.jar ， 检查压缩前的 apk 是 V2 签名的，压缩过后再次检测就不是 V2 签名了。

config 中的 property 配置如下：
    <issue id="property">
        <seventzip value="false"/>
        <metaname value="META-INF"/>
        <keeproot value="false"/>
    </issue>

签名文件是 .jks  文件，这个有影响吗？

**Comment by simpleton** [comment]
@Jimmy-J 你的配置似乎没有贴上，另外推荐使用gradle的方式集成。jar这边的版本升级有一些滞后，我稍后更新下。

**Comment by Jimmy-J** [comment]
刚刚试了一下使用 gradle 方式集成是正常的了，非常感谢

**Comment by imknown** [comment]
吊胃口... 我还是很好奇 问题怎么产生的...

**Comment by TracyZhangLei** [comment]
支持v2签名了么？还是我用的版本太老了

**Comment by simpleton** [comment]
@TracyZhangLei gradle从1.20开始支持，jar暂时还不支持
