### ISSUE TITLE
{CrashHandler$1.run--1} Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0

### ISSUE THREAD

**Issue by luguiyu** [shwenzhang/AndResGuard#156]
问题描述：
资源混淆成功之后，安装apk，进入第一个页面，点击按钮的时候应用crash，提示：Unable to resume activity , android.content.res.Resources$NotFoundException: String resource ID #0x0.
以下是我的配置：
![photo3](https://cloud.githubusercontent.com/assets/8243280/25803506/c06a468e-3429-11e7-8aab-9ff42d35e863.png)

这是我混淆之后的文件：
![photo2](https://cloud.githubusercontent.com/assets/8243280/25803449/81c51b34-3429-11e7-9de0-47ab8fb1bcfb.png)

**Comment by simpleton** [comment]
@luguiyu 应当是由于某sdk直接调用了`getIdentifier()`来获取资源，你需要把这些资源加入白名单中。

**Comment by luguiyu** [comment]
@simpleton 是这样的，点击该按钮后调整的页面有方法是调用getIdentifier()来获取资源，导致无法resume，已经找到了，谢谢了
