### ISSUE TITLE
请教一下问题

### ISSUE THREAD

**Issue by Caij** [shwenzhang/AndResGuard#157]
compressFilePattern = [
        "*.png",
        "*.jpg",
        "*.jpeg",
        "*.gif",
        "resources.arsc"
    ]    
是指通过7zip压缩文件 会影响图片的质量吗？
然后webp格式的图片支持吗？

谢谢

**Comment by simpleton** [comment]
@Caij 支持，这个只是改变资源在安装包里的压缩模式，不会改变图片本身的压缩模式。默认的打包方式使用的是使用Stored，这里的pattern是把存储方式改为Deflated。 是否启用7zip取决于你是否开启`use7zip = true`。
