### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by YMlion** [shwenzhang/AndResGuard#158]
不支持jdk-1.6，最新版`1.2.3`好像只支持jdk-1.8及以上，原来用`1.1.16`版本支持jdk-1.7及以上。

下面这个错误是最新版报的：

```
java.lang.UnsupportedClassVersionError:com/tencent/gradle/AndResGuardPlugin:Unsupported major.minor version 52.0
```

编译版本是不是应该降低一下，这个有点高啊，还有很多用1.6的。。。

**Comment by simpleton** [comment]
ok，收到。我稍晚再重新上传一个版本。

2017-05-18 16:15 GMT+08:00 YMlion <notifications@github.com>:

**Comment by simpleton** [comment]
@YMlion 你可以尝试下最新的master，然后麻烦试试localMaven后可否兼容。因为我本地暂时没有低版本的环境，所以麻烦你了。

**Comment by YMlion** [comment]
使用最新的master在**jdk-1.7** + **android gradle plugin-2.1.0**下测试没有问题了。

**Comment by simpleton** [comment]
@YMlion 多谢~

**Comment by simpleton** [comment]
1.2.3已经换包了，您可以刷新下缓存
