### ISSUE TITLE
在androidstudio preview 3.0 下 sync的时候会报错Error:Not valid.

### ISSUE THREAD

**Issue by tanweijiu** [shwenzhang/AndResGuard#159]
在androidstudio preview 3.0 下
sync的时候会报错：
Error:Not valid.

**Comment by simpleton** [comment]
@tanweijiu 收到，3.0还没有适配。

**Comment by tanweijiu** [comment]
@simpleton 静候您的适配。

**Comment by tanweijiu** [comment]
@simpleton 测试了下跟 classpath 'com.android.tools.build:gradle:3.0.0-alpha1'版本有关

**Comment by rexi1r** [comment]
i have the same problem.

**Comment by loody** [comment]
同上，报Error:Not valid.

**Comment by nestorm001** [comment]
I have the same problem with the gradle plugin version 3.0.0-alpha2

**Comment by netman44** [comment]
关掉就好了，但是混淆功能就没有了

**Comment by simpleton** [comment]
可以先暂时使用`classpath 'com.android.tools.build:gradle:2.3.3'` 版本，build tools还在alpha阶段，变化较大。
