### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by saantiaguilera** [shwenzhang/AndResGuard#160]
Hi there, does this takes into account resources referenced dynamically when obfuscating ? (I mean resources that are only used via `resources.getIdentifier(..., "my_resource_name");`)

This will obfuscate and shrink resources of dependencies (or other modules) ? The shrinkage isnt too important since `shrinkResources` does the same job, but the obfuscation seems really interesting :)

Also, do you have any benchmarks of how much did it reduced your size (taking into account the obfuscation + shrinkage + repackaging) ?

Thanks in advance!

**Comment by simpleton** [comment]
@saantiaguilera Hi, you need to add the resources which used via `getIndentifier` to the whiteList. 
The tooling didn't shrink any resources but only focus on obfuscate. And changed the store method of resources from Stored to Deflated in APK.

The reduced size of your APK is depended on the how many resources which stored in your APP. We wrote an [article](https://mp.weixin.qq.com/s?__biz=MzAwNDY1ODY2OQ==&mid=208135658&idx=1&sn=ac9bd6b4927e9e82f9fa14e396183a8f&mpshare=1&scene=1&srcid=0526KzozcGJ8mzgK88vFTozd&key=905e549481d6391f20cf0fad3501d0053e8d7b8c7cf9054c6e0672d04ea6de7c5f0629c9a707a6da94f8a9ddc6d3dedebb0adf869c140b52c7bc0cd741d29aa573bb43c3c2b07883adf18d4831ab8761&ascene=0&uin=Njg1NDg4NDQw&devicetype=iMac+MacBookPro11%2C2+OSX+OSX+10.12.5+build(16F73)&version=12020710&nettype=WIFI&fontScale=100&pass_ticket=PignfpkmBYZnvRwxLcJablfXHIkYrKFEzjhiAh2WAvnIWhMI7rM1P7%2BoR0B6tJMg) for expounding how this tooling works and how much it reduce the size of our APP(WeChat). But it is written by Chinese.
