### ISSUE TITLE
模块化开发方式下，如何使用这套方案

### ISSUE THREAD

**Issue by jiangyuseu** [shwenzhang/AndResGuard#166]
我们的app比较大，架构方式：业务模块以so的形式存在lib文件夹下，主工程里的资源文件比较少，通过你的这套方案，只能对主工程里的资源做混淆，业务模块的so文件理论上也可以按照这套方式解压并改arsc文件的方式，最后还原为so，这种只通过改后缀还原so的方式不可取吧？apk是通过apktool的方式还原的，so怎么还原呢？

**Comment by simpleton** [comment]
@jiangyuseu 我理解你的方案应该就是类似atlas的组件化方案。你们的so是独立的apk么？如果是独立的可能可以去适配。但你们整套的组件化方案对资源的访问应该是有一些专门的适配的，具体会有什么问题我这边不太清楚。

**Comment by jiangyuseu** [comment]
如果不依赖解包，并重新打包生成apk（感觉方案略重），是否有其他办法在打包过程中去做资源混淆

**Comment by simpleton** [comment]
打包过程可以直接修改aapt的流程，美团最早使用的这种方案。感觉这种更适合你这种场景。

**Comment by simpleton** [comment]
这里先关闭了，有其他问题可以再开issue
