### ISSUE TITLE
有个问题！使用应用宝的加固之后会有问题！

### ISSUE THREAD

**Issue by quelang9** [shwenzhang/AndResGuard#167]
使用adb 命令安装会报错：
        INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by quelang9** [comment]
刚才对比了应用宝加固后普通包和经过资源混淆后的包。发现普通包经过应用宝加固和签名以后包结构正常，但是资源混淆后的包被应用宝加固和签名后，签名信息找不到了。就是META-INF文件目录已经丢失了！！！！

**Comment by simpleton** [comment]
加固是在资源混淆之后，所以这个我这边也没什么办法可以fix。你试试再签一下名？
