### ISSUE TITLE
Obfuscate secret keys

### ISSUE THREAD

**Issue by ClaudeHangui** [shwenzhang/AndResGuard#168]
I am using Twitter, Facebook and Instagram in app for showing tweets, feeds....
Can I obfuscate the secret keys I used to register my app for these social networks ??

**Comment by simpleton** [comment]
@ClaudeHangui Sorry, the answer is NO. This tooling only makes your resources stored in a new short path to reduce your APK size. It wouldn't obfuscate or encrypt any other things.
