### ISSUE TITLE
gradle 方式集成后,得不到7zip的apk包

### ISSUE THREAD

**Issue by wll2007** [shwenzhang/AndResGuard#169]
andResGuard {
    // mappingFile = file("./resource_mapping.txt")
    mappingFile = null
    // 当你使用v2签名的时候，7zip压缩是无法生效的。
    use7zip = true
    useSign = true
    // 打开这个开关，会keep住所有资源的原始路径，只混淆资源的名字
    keepRoot = false
    whiteList = [
            // for your icon
            "R.drawable.icon",
            // for fabric
            "R.string.com.crashlytics.*",
            // for google-services
            "R.string.google_app_id",
            "R.string.gcm_defaultSenderId",
            "R.string.default_web_client_id",
            "R.string.ga_trackingId",
            "R.string.firebase_database_url",
            "R.string.google_api_key",
            "R.string.google_crash_reporting_api_key"
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
            "resources.arsc"
    ]
    sevenzip {
        artifact = 'com.tencent.mm:SevenZip:1.1.14'
        //path = "D:\\Program\7-Zip\7z.exe"
    }
}

签名也没有V2

**Comment by simpleton** [comment]
@wll2007 可以使用apksigner确认下apk是不是v2签名。在build tools2.2之后，默认使用v2签名。
