### ISSUE TITLE
只能生成两个apk

### ISSUE THREAD

**Issue by xiguanlejiuhao** [shwenzhang/AndResGuard#17]
运行时报错了，只生成了两个apk，app-release_signed.apk和app-release_unsigned.apk，我在环境变量里面已经配置7zip的路径和zipalign的路径，buildApk.bat的内容为：java -jar resourcesproguard.jar app-release.apk -config config.xml -out outapk -signature hello.jks hello123 hello123 Hello pause
并且config.xml中
。。。
seventzip value= "true" 
。。。，
 issue id="sign" isactive="true"
        path value ="C:\Users\user\Desktop\AndResGuard-master\work\hello.jks" 
        storepass value="hello123" 
        keypass value="hello123" 
        alias value="Hello" 
    issue
报错如下：
java.io.IOException: Cannot run program "7za": CreateProcess error=2, ?????????
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
请问该怎么解决？

**Comment by shwenzhang** [comment]
java.io.IOException: Cannot run program "7za": CreateProcess error=2, ?????????，找不到这个。可以手动传入7z的路径
