### ISSUE TITLE
用Androdi Studio命令行打包生成的apk没有经过7zip压缩

### ISSUE THREAD

**Issue by starry001** [shwenzhang/AndResGuard#172]
用gradlew resguardRelease 生成的apk包没有
 

![image](https://user-images.githubusercontent.com/11625352/28258363-785e1d6e-6b03-11e7-820c-c218ac0bb1eb.png)

**Comment by imknown** [comment]
> Note: Signature schemeV2 will make 7zip compressing invalid. If you really care about your APK size, please disable v2Signing in your signingConfigs

Copied from [README.md](https://github.com/shwenzhang/AndResGuard#andresguard)
