### ISSUE TITLE
AndResGuard-gradle-plugin gradle could not sync

### ISSUE THREAD

**Issue by Dwan-xie** [shwenzhang/AndResGuard#173]
Error:Could not find com.tencent.mm:AndResGuard-gradle-plugin:1.2.3.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.pom
    https://repo1.maven.org/maven2/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.jar
    https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.pom
    https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.jar

**Comment by devwangxiaogang** [comment]
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not find com.tencent.mm:AndResGuard-gradle-plugin:1.2.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.pom
         https://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/1.2.3/AndResGuard-gradle-plugin-1.2.3.jar
     Required by:
         project :****

**Comment by simpleton** [comment]
@Dwan-xie @devwangxiaogang sorry for this issue. Please add `maven { url 'https://dl.bintray.com/simsun/maven' } ` in your repositories as a workaround.

I'll fix it in few hours.

**Comment by Dwan-xie** [comment]
it's working now~

**Comment by KeqingLI** [comment]
`Task 'resguard' is ambiguous in root project 'XXX'. Candidates are: 'resguardDebug', 'resguardXXX', 'resguardXXXDebug', 'resguardXXXRelease', 'resguardRelease'``` 

`gradlew resguard release XXX`
请问是什么原因

**Comment by loody** [comment]
搞事情:grinning

**Comment by Dwan-xie** [comment]
Will change back to jcenter  in future？

**Comment by simpleton** [comment]
Yep, we will change back when jcenter approves our new accounts request.

**Comment by KeqingLI** [comment]
maven{ url 'https://dl.bintray.com/wemobiledev/maven'}

**Comment by captain-miao** [comment]
https://dl.bintray.com/simsun/maven/com/tencent/mm/AndResGuard-gradle-plugin/1.2.13/AndResGuard-gradle-plugin-1.2.13.pom

**Comment by simpleton** [comment]
这个issue很早都close了，`maven { url 'https://dl.bintray.com/simsun/maven' }
`只是一个临时方案，现在不再需要了。

**Comment by himanshi-coder** [comment]
Hi, i was facing this issue since 3 days and not able to resolve since i was getting this error continuously 

===========
   > Could not resolve all task dependencies for configuration ':classpath'.
      > Could not find com.tencent.mm:AndResGuard-gradle-plugin:1.2.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/com/tencent/mm/AndResGuard-gradle-plugin/1.2.0/AndResGuard-gradle-plugin-1.2.0.pom
          - https://repo.maven.apache.org/maven2/com/tencent/mm/AndResGuard-gradle-plugin/1.2.0/AndResGuard-gradle-plugin-1.2.0.pom
          - https://jitpack.io/com/tencent/mm/AndResGuard-gradle-plugin/1.2.0/AndResGuard-gradle-plugin-1.2.0.pom
          - https://maven.fabric.io/public/com/tencent/mm/AndResGuard-gradle-plugin/1.2.0/AndResGuard-gradle-plugin-1.2.0.pom
        Required by:
            project :
=============================

then at last i started serching the url which can give me AndResGuard-gradle-plugin-1.2.0.pom file instead of 404 error 

i go through multiple links and then i found a link -
https://repo1.maven.org/maven2/io/github/leon406/AndResGuard-gradle-plugin/1.2.22.6/AndResGuard-gradle-plugin-1.2.22.6.pom

which was returning some piece of code instead of 404 

i implemented it like this in my code project level build.gradle file 

===========
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        jcenter()
        google()
        mavenCentral()   // --> Ensure this is included for the plugin dependency
        maven { url 'https://maven.fabric.io/public' }
    dependencies {

        classpath("com.android.tools.build:gradle:7.2.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath 'com.google.gms:google-services:4.3.15'
        // Corrected AndResGuard plugin dependency
        classpath 'io.github.leon406:AndResGuard-gradle-plugin:1.2.22.6'  // Use exact version from Maven Central
    }
}
================= 
and it worked 

i hope it will work for you as well thanks
