### ISSUE TITLE
Use version 1.2.3, output apk didn't have 7zip in name.

### ISSUE THREAD

**Issue by Dwan-xie** [shwenzhang/AndResGuard#175]
I have another question.
Use version 1.2.3, Output apk didn't have 7zip in name.
xxxxxxxxx_aligned_signed.apk

Use version 1.1.16
xxxxxxxxx_signed_7zip_aligned.apk

What's the difference between the two versions? 
Or maybe i should change some config?

**Comment by simpleton** [comment]
Note: Signature schemeV2 will make 7zip compressing invalid. If you really care about your APK size, please disable v2Signing in your signingConfigs

**Comment by Dwan-xie** [comment]
Ok, I will try this. 
But in my project , i don't use v2Signing

**Comment by simpleton** [comment]
V2sign is enabled defaultly when build tools version is greater than 2.2

**Comment by Dwan-xie** [comment]
it's work, thanks~
