### ISSUE TITLE
请问这个插件可以针对aar打包进行优化吗

### ISSUE THREAD

**Issue by BryanSharp** [shwenzhang/AndResGuard#176]
如题，貌似没有找到这方面的文档

**Comment by simpleton** [comment]
不行，针对的是apk。因为aar的资源app工程可能会使用，混淆了并不好。且最后和apk一起混淆效果是等效的

**Comment by jayclf** [comment]
不行，应该只针对的是APK，不过改改应该是可以支持aar的

**Comment by BryanSharp** [comment]
了解，作为SDK开发者，混淆aar的需求还是很强烈的

**Comment by simpleton** [comment]
@BryanSharp 因为aar是可以导出资源给app使用的，你觉得这个要怎么界定呢？

**Comment by KobeBryant824** [comment]
aar给别的公司使用呢 @simpleton
