### ISSUE TITLE
./gradlew resguardDebug不混淆（ProGuard）

### ISSUE THREAD

**Issue by leleliu008** [shwenzhang/AndResGuard#179]
您好，我在使用过程中遇到如下的问题：

在Debug模式下，打开了混淆的开关，如下：
`
buildTypes {
        debug {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-project-debug.txt'
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-project-release.txt'
        }
    }
`
但是使用./gradlew resguardDebug却不进行混淆（ProGuard），而./gradlew resguardRelease是进行混淆（ProGuard）的。
使用./gradlew assembleDebug和./gradlew assembleRelease都是可以进行混淆（ProGuard）的。

**Comment by simpleton** [comment]
请确认assembleDebug是进行ProGuard的，resguardDebug只是简单依赖了assembleDebug

**Comment by leleliu008** [comment]
是的，由于我没有使用./gradlew clean清除缓存，所以没有执行，我执行了./gradlew clean之后就正常了。可以关闭这个问题了，我的问题，感谢！
