### ISSUE TITLE
keeproot=false，反编译apk后，res路径仍然为原路径，没有被混淆，

### ISSUE THREAD

**Issue by ForeverARookie** [shwenzhang/AndResGuard#180]
使用微信混淆过后的apk，直接解压出来的res文件夹被混淆成r/a/...，但使用反编译工具反编译后，res文件夹的路径却是完整显示，就好像设置了keeproot为true。

**Comment by simpleton** [comment]
直接解压是r/a就说明工具是OK的，至于反编译后是完整的的具体看反编译工具是如何找回这个信息的，可否提供一下反编译工具的link

**Comment by ForeverARookie** [comment]
使用的是apktool，https://ibotpeaches.github.io/Apktool/。
官网最新版本是2.2.4，我使用的是2.2.2。

**Comment by simpleton** [comment]
@ForeverARookie 我试了下，apktools反编译出来的资源远比apk解压出来的多，具体得看一下他的代码。

**Comment by ForeverARookie** [comment]
ok。如果能够在接下来的版本解决这个问题当然是棒棒哒，当然如果觉得无关紧要的话也无妨，先忙去啦~感谢回复！have a nice day~
