### ISSUE TITLE
encrypt all strings

### ISSUE THREAD

**Issue by rexi1r** [shwenzhang/AndResGuard#181]
hi, @simpleton  do you think you can encrypt all strings in strings.XML and decrypt at runtime?

**Comment by simpleton** [comment]
@rexi1r I think encrypting all strings is a different topic. AndResGuard won't change the android resource management mechanism. But encrypting strings need to hijack android resource reading method. 
I found some guys put some confidential data in native lib. [This blog](http://drakeet.me/android-security-guide/) describes the details, but it's written in Chinese.

**Comment by rexi1r** [comment]
@simpleton Thank you for your prompt reply, that's surprised me.
but I think res guard that includes strings and other values.
