### ISSUE TITLE
Style name stays same in layout files

### ISSUE THREAD

**Issue by LynxKik** [shwenzhang/AndResGuard#182]
Hey, I used the command line to obfuscate my android res, but when I recompile the @style/ stays the same name as original so if the resource named @style/apptheme to @style/a the layout file still says @style/apptheme

**Comment by simpleton** [comment]
Hi @LynxKik, I didn't understand your issue very clearly. Could you supply a simple sample for describing your issue or some details?

**Comment by LynxKik** [comment]
@Style/xxx does not get obfuscated is what I'm trying to say.

**Comment by LynxKik** [comment]
Cannot recompile after decompiling apk obfuscated by AndResGuard here is APKTool Log: https://hastebin.com/izocuhigiq.tex   

I'm guessing the @ styles/xxx does not get obfuscated
