### ISSUE TITLE
gradle中配置mappingFile，混淆成功后，对应的mapping文件没有更新

### ISSUE THREAD

**Issue by ForeverARookie** [shwenzhang/AndResGuard#184]
我把mapping的txt放在工程目录的AppMain下，并配置mappingFile = file("./resource_mapping.txt")，名称正确。但在添加新的id后，重新进行混淆，在混淆输出的文件夹中的mapping文件中，有新增加的id混淆，AppMain下的mapping文件并没有修改的痕迹和记录。

**Comment by simpleton** [comment]
@ForeverARookie 我没有看懂你的问题，您是指mapping文件输出的没有新增的id么？

**Comment by ForeverARookie** [comment]
是的，指定mapping文件咩有新增的id

**Comment by ForeverARookie** [comment]
![image](https://user-images.githubusercontent.com/9671793/29646062-bf34229c-88b3-11e7-99b3-22323726a87d.png)
![image](https://user-images.githubusercontent.com/9671793/29646134-282ce6a8-88b4-11e7-989c-87c26a5d3d25.png)

使用命令行操作时，在config中配置了keepmapping路径，日志输出如上，resource_mapping.txt也没有被更新。
@simpleton

**Comment by ForeverARookie** [comment]
![image](https://user-images.githubusercontent.com/9671793/29646252-ed42d9de-88b4-11e7-8483-2ecb82a804b4.png)
![image](https://user-images.githubusercontent.com/9671793/29646264-ff3cffa2-88b4-11e7-8e0c-04772112d5fb.png)
在config中配置了keepmapping路径，输出日志如图1，resource_mapping.txt文件未被更新。
@simpleton

**Comment by simpleton** [comment]
@ForeverARookie 收到，我今天debug下。

**Comment by simpleton** [comment]
@ForeverARookie 是不会更新你的input mapping的，会更新在output下。我这边尝试了下，是可以更新的。

**Comment by ForeverARookie** [comment]
所以keepmapping选项的作用是指定旧的mapping文件，参照指定路径的旧的mappping文件输出新的mapping文件在output目录下，从而保持一致性，并不是直接更新指定路径的mapping文件。这样子理解对吧？

**Comment by simpleton** [comment]
@ForeverARookie 是的

**Comment by ForeverARookie** [comment]
@simpleton 多谢解答。是我之前的理解出了问题。谢谢！

**Comment by ForeverARookie** [comment]
如果能直接更新指定路径resources_mapping.txt文件，就免去了再把output文件夹中的mapping文件再覆盖resources_mapping.txt的操作。
@simpleton

**Comment by simpleton** [comment]
@ForeverARookie 可以通过gradle脚本或者别的脚本copy过去，主要每个用户的需求不太一样。保留原始的更新的应该没什么问题。
