### ISSUE TITLE
META-INF被占用的问题

### ISSUE THREAD

**Issue by XavierSAndroid** [shwenzhang/AndResGuard#185]
在做一些组件的时候会用到META-INF，AndResGuard处理之后都丢了。目测代码里直接忽略了META-INF目录，看看可以改成只忽略签名的几个文件吗？

**Comment by simpleton** [comment]
收到，可以再具体表述一下你的问题么？方便我这边复现和debug

**Comment by XavierSAndroid** [comment]
@simpleton 就是例如放了一些文件到『src/main/resources/META-INF/xxx/』目录下，普通打包时可以打到apk的META-INF里的，跑完AndResGuard文件就丢失了。

**Comment by simpleton** [comment]
@
