### ISSUE TITLE
在white list增加R.id.* 遇到问题

### ISSUE THREAD

**Issue by van416** [shwenzhang/AndResGuard#188]
因为项目比较大的问题，暂时升级不了1.2.3的包，之前用的是1.1.10，当我加上R.id.*的时候，出现了崩溃

com.tencent.mm.android.AndrolibException:writeSpecNameStringBlock length is different name 12, tempByte14
at com.tencent.mm.androlib.res.decoder.StringBlock.writeSpecNameStringBlock(StringBlock.java:134)

版本是1.1.10

去掉"R.id.*"就能正常打包，怎么回事呢，要如何配置才能让id不被混淆呢

另外：能帮忙把tag 1.1.10->1.1.20之前的包上传到jcenter吗。谢谢
http://jcenter.bintray.com/com/tencent/mm/AndResGuard-gradle-plugin/

**Comment by simpleton** [comment]
因为jcenter要求公司domain的都放在公司账户下，andresguard被下架了一次，然后重新在公司账户发布了，就没发历史版本。
你可以添加https://dl.bintray.com/simsun/maven 在你的maven源里，然后就可以引用到1.1.16了

**Comment by simpleton** [comment]
ref #129

**Comment by simpleton** [comment]
plz try 1.2.5

**Comment by David-Kuper** [comment]
我最近也遇到这个问题。公司是用的1.2.16的版本，项目太大一时没有办法升级到1.2.5版本；请问这个问题有低版本的Fix可以用吗？或者修复的办法是什么，我fork一个仓库出来cherry-pick一下🙏.
