### ISSUE TITLE
友盟登录以及分享需要添加白名单

### ISSUE THREAD

**Issue by yemengsky** [shwenzhang/AndResGuard#19]
<issue id="whitelist" isactive="true">
         
         
         

    <path value ="yourpackagename.R.string.umeng*" />	
    <path value ="yourpackagename.R.layout.umeng*" />
    <path value ="yourpackagename.R.drawable.umeng*" />
    <path value ="yourpackagename.R.anim.umeng*" />
    <path value ="yourpackagename.R.color.umeng*" />
    <path value ="yourpackagename.R.style.*UM*" />
    <path value ="yourpackagename.R.style.umeng*" />
     <path value ="yourpackagename.R.id.umeng*" />

    </issue>

**Comment by simpleton** [comment]
add in readme
