### ISSUE TITLE
gradle脚本里怎么写忽略规则

### ISSUE THREAD

**Issue by zhangkehu** [shwenzhang/AndResGuard#190]
通过context.getResources().getIdentifier()获取一些被混淆的资源会有问题，所以问一下怎么在gradle脚本里配置白名单
whiteList = [
            // for your icon
            "R.string.umeng*",
            "R.string.UM*",
            "R.string.tb_*",
}
这个貌似只能处理id，怎么配置文件某个图片名不被混淆？

**Comment by simpleton** [comment]
是绝对路径么？可以用过mapping来做

**Comment by zhangkehu** [comment]
理想的应该是相对路径，想跟着工程目录走。我看你们gradle脚本里有mappingFile = file("./resource_mapping.txt")；但不清楚这个怎么用。文档里都是说通过命令行操作时候怎么配置白名单和mapping规则。

**Comment by simpleton** [comment]
比如你想keep res目录下的mipmap的路径就像如下写就行了，左边是你资源的工程路径，右边是被keep的路径。
```
res path mapping:
    res/mipmap-hdpi-v4 -> res/mipmap-hdpi-v4
    res/mipmap-mdpi-v4 -> res/mipmap-mdpi-v4
    res/mipmap-xhdpi-v4 -> res/mipmap-xhdpi-v4
    res/mipmap-xxhdpi-v4 -> res/mipmap-xxhdpi-v4
    res/mipmap-xxxhdpi-v4 -> res/mipmap-xxxhdpi-v4
```

**Comment by zhangkehu** [comment]
ok，我等会儿验证一下，我现在不用getIdentifier获取那些资源了。

**Comment by zhangkehu** [comment]
我发现通过getIdentifier()获取资源遇到的问题可以通过whiteList这里解决，我不需要单独去keep住路径，例如我今天遇到的一些emoji的表情图片，whiteList写法可以是：
```
whiteList = [
            // for your icon
            "R.string.umeng*",
            //for some emoji
            "R.drawable.emoji_+_+",
]
```
这样
擦，github图片死活传不上去，放laji百度好了：https://pan.baidu.com/s/1o89oahk
