### ISSUE TITLE
按照你的顺序使用 使用apktool的时候 res包的下资源还是没有混淆，请帮忙看下

### ISSUE THREAD

**Issue by LJame** [shwenzhang/AndResGuard#192]
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.3'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'AndResGuard'
andResGuard {
//     mappingFile = file("./resource_mapping.txt")
    mappingFile = null
    // It will be invalid when you sign apk with schemeV2
    use7zip = true
    useSign = true
    // it will keep the origin path of your resources when it's true
    keepRoot = false
    whiteList = [
            // your icon
            "R.drawable.three_year_logo",
            "R.string.app_name",
    ]
    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
            "*.gif",
            "resources.arsc"
    ]
    sevenzip {
//        artifact  = 'com.tencent.mm:SevenZip:1.2.3'
        //path = "/usr/local/bin/7za"
        path="F:/developSoftWare/7z1701-x64.exe"
    }
}
android {
  
    dexOptions {
        jumboMode true
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

        instrumentTest.setRoot('tests')
    }
    defaultConfig {
        aaptOptions.cruncherEnabled = false
        aaptOptions.useNewCruncher = false
    }
    compileSdkVersion 21
    buildToolsVersion '25.0.0'

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

ext {
    // Sdk and tools
    minSdkVersion = 11
    targetSdkVersion = 21
    compileSdkVersion = 21
    buildToolsVersion = "25.0.0"
    versionCode = 26
}

**Comment by simpleton** [comment]
请直接解压确认，apktool反编译出来会尝试不全一些路径，但不一定正确，具体原理我还没有研究。

**Comment by simpleton** [comment]
ref #182

**Comment by LJame** [comment]
我直接解压 确认了 还是没有混淆呢 我是用V2(Signatrue Versions)

**Comment by simpleton** [comment]
这和签名无关的，请提供相关编译log，我看下。

**Comment by LJame** [comment]
Executing tasks: [:assembleRelease]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to D:\SDK\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

useNewCruncher has been deprecated. It will be removed in a future version of the gradle plugin. New cruncher is now always enabled.
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:extractProguardFiles
:preReleaseBuild
:checkReleaseManifest
:prepareReleaseDependencies
:compileReleaseAidl UP-TO-DATE
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources UP-TO-DATE
:processReleaseManifest UP-TO-DATE
:processReleaseResources UP-TO-DATE
:generateReleaseSources UP-TO-DATE
:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileRelease
:compileReleaseJavaWithJavac UP-TO-DATE
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources UP-TO-DATE
:lintVitalRelease
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets UP-TO-DATE
:processReleaseJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:transformClassesAndResourcesWithProguardForRelease UP-TO-DATE
:transformClassesWithDexForRelease UP-TO-DATE
:mergeReleaseJniLibFolders UP-TO-DATE
:transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
:validateSigningRelease
:packageRelease UP-TO-DATE
:assembleRelease

BUILD SUCCESSFUL

Total time: 8.452 secs

**Comment by simpleton** [comment]
你没有运行正确的task...请运行resguard[BuildType]相关的task

**Comment by LJame** [comment]
我新建了一个新工程，
 buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
我没有其他的需求 不需要加啥，还是直接解压没有混淆啊，没明白，麻烦你了

**Comment by simpleton** [comment]
Executing tasks: [:assembleRelease]。请执行resguardRelease

**Comment by LJame** [comment]
Execution failed for task ':app:compileReleaseJavaWithJavac'.
> Could not find tools.jar. Please check that F:\JDK contains a valid JDK installation.
build failed
弄了命令行以后出现上面的报错

**Comment by simpleton** [comment]
这个错误感觉和AndResGuard无关了

**Comment by LJame** [comment]
好的  谢谢 这个问题可以关了
