### ISSUE TITLE
友盟分享添加了白名单还是不能分享

### ISSUE THREAD

**Issue by taoziG** [shwenzhang/AndResGuard#193]
按照文档添加了友盟社会分享的白名单还是报错，
错误日志为：
AndroidRuntime(29311): java.lang.RuntimeException: 缺少资源文件
NotificationService(1204): Not posting notification without small icon: Notification(pri=0 contentView=com.xx.xx.xx/0xa03004a vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 vis=PRIVATE)
请问为什么帮忙解决下谢谢

**Comment by simpleton** [comment]
因为这个白名单是一些用户和我一起PR的。使用版本可能已经旧了，也欢迎你的PR

**Comment by taoziG** [comment]
将友盟的资源全部找出添加了白名单就可以了有重复没有整理
  <path value="包名.R.string.umeng*"/>
        <path value="包名.R.layout.umeng*"/>
        <path value="包名.R.layout.socialize_*"/>
        <path value="包名.R.drawable.umeng*"/>
        <path value="包名.R.anim.umeng*"/>
        <path value="包名.R.color.umeng*"/>
        <path value="包名.R.color.umeng_*"/>
        <path value="包名.R.style.*UM*"/>
        <path value="包名.R.style.umeng*"/>
        <path value="包名.R.id.umeng*"/>
        <path value="包名.R.string.UM*"/>
        <path value="包名.R.string.umeng_*"/>
        <path value="包名.R.string.umeng*"/>
        <path value="包名.R.string.tb_*"/>
        <path value="包名.R.layout.tb_*"/>
        <path value="包名.R.drawable.tb_*"/>
        <path value="包名.R.color.tb_*"/>
        <path value="包名.R.drawable.sina*"/>
         <path value="包名.R.drawable.qq_*"/>
         <path value="包名.R.drawable.umeng_"/>
        <path value="包名.R.drawable.umeng_socialize_*"/>
        <path value="包名.R.layout.*messager*"/>
        <path value="包名.R.id.*messager*"/>
        <path value="包名.R.id.progress_bar_parent"/>
         <path value="包名.R.id.socialize_*"/>
        <path value="包名.R.id.webView"/>
        <path value="包名.R.drawable.tb_*"/>
