### ISSUE TITLE
使用命令打包后V2的签名变成了V1

### ISSUE THREAD

**Issue by Caij** [shwenzhang/AndResGuard#194]
java -jar AndResGuard-cli-1.2.3.jar /Users/caij/Desktop/outputs/apk/emore-armeabi-release-3.6.0-56.apk -config AndResGuardConfig.xml -signature xxx xxx xxx xxxx -zipalign /Users/caij/Library/Android/sdk/build-tools/26.0.0/zipalign

使用这个命令v2签名的apk打包完成变成了v1签名的。  是少了什么配置吗？
[AndResGuardConfig.txt](https://github.com/shwenzhang/AndResGuard/files/1288226/AndResGuardConfig.txt)

**Comment by simpleton** [comment]
jar这边没有集成apksigner，需要再用apksigner重签下

**Comment by Caij** [comment]
我想问下
package_unsigned 这个包有没有align对齐？
package_signed 这个包有没没align对齐？（一般都不是先对齐再签名吗）
package_signed_aligned 这个是包是先签名再对齐的吗？

**Comment by simpleton** [comment]
v1是的，顺序为 签名->7zip压缩->对齐
v2的顺序为，对齐->签名。
