### ISSUE TITLE
输出apk命名问题

### ISSUE THREAD

**Issue by dijiubuzhan** [shwenzhang/AndResGuard#195]
用AndResGuard打包apk每次都会输出aligned_signed.apk，aligned_unsigned.apk，unsigned.apk以及其他apk，感觉好多呀，可以设置只输出一个apk吗

**Comment by simpleton** [comment]
这些都是一些中间产物，用来方便debug的。本身1.2.5之后的版本会自动覆盖你原先assemble task的输出，只需关心这个就OK了。

另外也有一个optional的属性
```
/**
* Optional: if finalApkBackupPath is null, AndResGuard will overwrite final apk
* to the path which assemble[Task] write to
*/
finalApkBackupPath = "${project.rootDir}/final.apk"
```
