### ISSUE TITLE
gradle 方式下集成，如何修改签名算法？

### ISSUE THREAD

**Issue by Realbbyz** [shwenzhang/AndResGuard#197]
目前默认是SHA1，希望切换到SHA256

**Comment by simpleton** [comment]
暂时没有导出这个属性，下个版本会增加设置项。

**Comment by Realbbyz** [comment]
OK，多谢

**Comment by Realbbyz** [comment]
再追问下，下个版本大概计划什么时间发布？

**Comment by simpleton** [comment]
准备周末

**Comment by Realbbyz** [comment]
太好了，非常感谢及时回复，扩展设置项的使用规则也请在新版本中明示。

**Comment by simpleton** [comment]
plz try 1.2.7

**Comment by Realbbyz** [comment]
Hi, @simpleton 

试用了1.2.7和1.2.8，发现增加 digestalg = "SHA256" 参数后，不管是V1还是V2签名，混淆后的版本都有问题，APK大小变为1KB。

 @看了下修改这个问题的代码，下面这一块变量的赋值是不是有点问题？

![1124](https://user-images.githubusercontent.com/21209858/33194878-002cb1f4-d10e-11e7-8770-95e47f4e8f44.png)

**Comment by simpleton** [comment]
@Realbbyz 有什么问题？

**Comment by Realbbyz** [comment]
左边的参数名是不是少了个e，我看后面调用的都是带e的？

**Comment by simpleton** [comment]
嗯，那个只是log，不碍事的。但你提的现象确实存在。我还在fix中

**Comment by simpleton** [comment]
1K的原因是签名失败，原先的签名算法的名称写的有错误，需要添加-，比如（SHA-256)。你可以更新到1.2.9，这个版本如果签名失败会throw出exception，不会继续剩下的流程.
