### ISSUE TITLE
Failed to resolve attribute at index 1: TypedValue

### ISSUE THREAD

**Issue by a137235** [shwenzhang/AndResGuard#198]
@simpleton 会将所有的?attr/去掉，如："?attr/d1"替换成"?d1"，就会直接报以上错误，版本为1.2.6

**Comment by simpleton** [comment]
@a137235 可能是个bug，你这边可以先用回1.2.3的版本试试。

**Comment by a137235** [comment]
我这个有个错误1.2.6才解决的，没法试1.2.3呀

**Comment by simpleton** [comment]
OK，收到。你要不发一下你未混淆的包，我这边fix了通知你

**Comment by a137235** [comment]
已上传，worldad.cn/app-debug.apk

**Comment by simpleton** [comment]
@a137235 你传的这个包似乎是资源混淆后的，我需要的是混淆前的包

**Comment by simpleton** [comment]
@a137235 你这里?attr/具体指的是去访问的属性么？可否给出可以复现错误的代码片段？

**Comment by a137235** [comment]
@simpleton 未混淆包已经替换，直接xml引用就报错了，我检查混淆后的xml就少了?attr/。

**Comment by simpleton** [comment]
@a137235 我这边用你提供的apk混淆后可以运行起来，出错的点是哪里呢？

另外我在sample中简单增加了，并没有复现问题。这个是需要如何配置才可以复现呢？
```xml
<TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:textColor="?attr/colorPrimary"/>
```

**Comment by a137235** [comment]
@simpleton 出错点在三个点菜单那里，具体原因我也没仔细分析。

**Comment by simpleton** [comment]
@a137235 没混淆的apk，点菜单也会crash...

**Comment by a137235** [comment]
额忘记测试原包了，那就对不起了耽误你时间了。

**Comment by simpleton** [comment]
没事，我这边先close了。有别的问题再提issue
