### ISSUE TITLE
Error: Could not get unknown property 'apkVariantData'

### ISSUE THREAD

**Issue by DummyCo** [shwenzhang/AndResGuard#199]
Hi there! Getting next error while gradle project sync with Android 3.0 Beta 6. Is it related to `com.android.tools.build:gradle:3.0.0-beta6` support?

`
Error:Could not get unknown property 'apkVariantData' for object of type com.android.build.gradle.internal.api.ApplicationVariantImpl.
`

**Comment by simpleton** [comment]
@DummyCo We haven't supported `com.android.tools.build:gradle:3.0.0` yet， because of Google doesn't release the source code or documents for this repo. You can use 2.x version for a workaround.

We'll adapt the latest `com.android.tools.build:gradle` ASAP when google relaesed it.

ref #159
