### ISSUE TITLE
没有7za命令异常，已安装7z并且将7z安装目录加入到了环境变量

### ISSUE THREAD

**Issue by boybeak** [shwenzhang/AndResGuard#20]
是这样的，我下载的7z是最新的15.09beta版本，在安装目录下，我也没有发现有7za.exe，是否是我安装的7Z版本的问题？

**Comment by paulchang1990** [comment]
@boybeak 官网15.10 beta：7-Zip Extra: standalone console version, 7z DLL, Plugin for Far Manager版本包含7za.exe

**Comment by shwenzhang** [comment]
read the lastest README
