### ISSUE TITLE
直接对apk执行7zip压缩导致apk无法启动

### ISSUE THREAD

**Issue by getandset** [shwenzhang/AndResGuard#200]
试了对我们的apk进行7z压缩，无论通过什么配置，签名后进行7zip压缩生产的apk包都是无法启动的。到签名这一步还是正常的。还看不到有用的崩溃日志，有解吗？

**Comment by simpleton** [comment]
@getandset 是使用AndResGuard来压缩的么？你提供的信息太少了，暂时无法诊断问题。贴一下编译和运行时的log吧

**Comment by HDHunter** [comment]
启动的过程，系统会打印基本的log。。如果IDE没打印出来，可以直接shell logcat打印。

**Comment by getandset** [comment]
用AndResGuard打包的日子如下：
java -jar AndResGuard-cli-1.2.6.jar bigolive-3.10.1-549-official.apk -zipalign /Users/thomas/AndResGuard/tool_output/zipalign 
reading config file, /Users/thomas/AndResGuard/tool_output/config.xml
mKeepRoot true
convertToPatternString typeName layout format .*
convertToPatternString typeName anim format .*
convertToPatternString typeName id format .*
convertToPatternString typeName string format .*
convertToPatternString typeName color format .*
convertToPatternString typeName menu format .*
convertToPatternString typeName style format .*
convertToPatternString typeName xml format .*
convertToPatternString typeName raw format .*
convertToPatternString typeName attr format .*
convertToPatternString typeName drawable format .*
convertToPatternString typeName dimen format .*
convertToPatternString typeName array format .*
convertToPatternString typeName integer format .*
convertToPatternString typeName bool format .*
convertToPatternString typeName animator format .*
[AndResGuard] begin: null, bigolive-3.10.1-549-official.apk
unziping apk to /Users/thomas/AndResGuard/tool_output/bigolive-3.10.1-549-official/temp
decoding resources.arsc
parse to get the exist names in the resouces.arsc first
reading packagename sg.bigo.live
resources mapping file /Users/thomas/AndResGuard/tool_output/bigolive-3.10.1-549-official/resource_mapping_bigolive-3.10.1-549-official.txt done
writing new resources.arsc 
resources.arsc Character Encoding: utf-8
General unsigned apk: bigolive-3.10.1-549-official_unsigned.apk
DestResDir 4185 rawResDir 4185
signing apk: bigolive-3.10.1-549-official_signed.apk
signature Algorithm is: SHA1withRSA
use 7zip to repackage: bigolive-3.10.1-549-official_signed_7zip.apk, will cost much more time
[addStoredFileIn7Zip]rewrite the stored file into the 7zip, file count:2131
zipaligning apk: bigolive-3.10.1-549-official_signed.apk
zipaligning apk: bigolive-3.10.1-549-official_signed_7zip.apk
[AndResGuard] done, total time cost: 32.311000s
[AndResGuard] done, you can go to file to find the output /Users/thomas/AndResGuard/tool_output/bigolive-3.10.1-549-official

对config.xml加了白名单处理，所有通过R引用的资源都加进了白名单。生成的apk文件知道签名这一步的apk都是可以正常运行的，直到zip压缩这一步生成的apk是无法运行的。

7zip压缩后，运行apk的error log：
10-01 18:33:33.757 730-764/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
10-01 18:33:33.757 730-764/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
10-01 18:33:35.716 31758-31834/? E/YYMedia: [YYMediaService]create output dir failed.
10-01 18:33:36.421 914-1189/? E/InputDispatcher: channel '9121456 sg.bigo.live/sg.bigo.live.login.LoginActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-01 18:33:36.915 2501-2501/? E/ctxmgr: [WorkInfo]Attribution was already enqueued errorCode=8, pkg=com.google.android.gms, lbl=UserVelocityProducer_receive, start=2017-10-01 18:32:31.267-0400, stop=2017-10-01 18:32:31.267-0400, durtn=0ms.
10-01 18:33:36.917 2501-2501/? E/ctxmgr: [WorkInfo]Attribution was already enqueued errorCode=8, pkg=com.google.android.gms, lbl=UserVelocityProducer_receive, start=2017-10-01 18:32:31.267-0400, stop=2017-10-01 18:32:31.267-0400, durtn=0ms.
10-01 18:33:36.940 2501-30889/? E/ctxmgr: [WorkManager]Ongoing task not found: UserVelocityProducer_receive
10-01 18:33:36.941 2501-30889/? E/ctxmgr: [WorkManager]Ongoing task not found: UserVelocityProducer_receive
10-01 18:33:37.601 31798-31836/? E/bigolive-app: [LogSender]uploading -> http for release ver.

和我们应用相关的就只有sg.bigo.live/sg.bigo.live.login.LoginActivity这一句。麻烦了。。

**Comment by simpleton** [comment]
@getandset 要不你把你的相关apk发一下我debug下。7zip相关有一个已知问题就是 #162

**Comment by getandset** [comment]
http://down.bigo.tv/android/bigolive-bigotv.apk

apk下载地址

**Comment by getandset** [comment]
这个能debug出什么吗？

**Comment by simpleton** [comment]
@getandset 不好意思，前面有点其他事情忘记帮你debug了，十分抱歉。刚才看了下，你们jni是否有加密的逻辑？或者什么别的特殊逻辑呢？
```
09-29 20:41:59.678 1846-482/? E/ActivityTrigger: activityResumeTrigger: not whiteListedsg.bigo.live/com.yy.iheima.startup.SplashActivity/545
09-29 20:41:59.753 3250-3439/? W/WtProcessStrategy: process sg.bigo.live uid 10220 pid 30479 start duration is too short!  Start:1506742919694 Current:1506742919753
09-29 20:41:59.953 30479-30479/? W/ResourceType: No package identifier when getting value for resource number 0x00000000
09-29 20:42:00.032 30479-30552/? E/YYMedia: [YYMediaService]create output dir failed.
```

**Comment by getandset** [comment]
JNI没有加密或者其他处理。7z压缩不是只是对资源文件和resources.arsc 进行压缩吗？对so文件应该没有做处理吧。把AndResguard集成到gradle打包是OK的。用命令行对apk在压缩就出现这个问题了

**Comment by simpleton** [comment]
OK，您这边可以先使用gradle，命令行工具我再查看下是什么问题。

**Comment by simpleton** [comment]
希望大家还是都切换到gradle，命令行的工具会慢慢的不再维护。
