### ISSUE TITLE
打出的apk 无法安装

### ISSUE THREAD

**Issue by funset** [shwenzhang/AndResGuard#201]
之前还可以的 没有修改andresguard的配置。只是修改了代码，现在打包无法安装提示安装包可能损坏
andResGuard {
        mappingFile = null
        use7zip = true
        useSign = true
        keepRoot = false
        whiteList = [
                "com.xx.xx.R.drawable.ic_launcher"
        ]
        compressFilePattern = [
                "*.png",
                "*.jpg",
                "resources.arsc"
        ]

        sevenzip {
            artifact = 'com.tencent.mm:SevenZip:1.2.6'
        }
    }

**Comment by funset** [comment]
app-release_aligned_signed.apk

**Comment by simpleton** [comment]
ok，我这里先close了。
