### ISSUE TITLE
Could the collaborators create some unstable branch like `develop`?

### ISSUE THREAD

**Issue by imknown** [shwenzhang/AndResGuard#204]
For further testing pull-requests.

**Comment by simpleton** [comment]
OK, I'll create one

**Comment by imknown** [comment]
Could I request this [`pull request`](https://github.com/shwenzhang/AndResGuard/compare/master...imknown:pr-AS-3.0.0-Compat?expand=1) ?

**Comment by simpleton** [comment]
Of course, thx a lot.

**Comment by imknown** [comment]
@simpleton :)
