### ISSUE TITLE
使用AS3.0，AndResGuard 1.2.8-RC1，打包之后的apk只有1k

### ISSUE THREAD

**Issue by ml0728119** [shwenzhang/AndResGuard#206]

**Comment by ml0728119** [comment]
但是能够获得一个unsigned的压缩后的apk为正常大小

**Comment by simpleton** [comment]
可否提供一下基础包，我debug下？

**Comment by simpleton** [comment]
sample似乎没有问题，也请提供一下使用的AS的buildt-tools的版本，是否为release版本呢？

**Comment by ml0728119** [comment]
原始包已经发到你QQ邮箱了，请查收。github上文件发了好几次都失败了。
com.android.tools.build:gradle:3.0.0。release版本。

我也运行过sample，确实能够压出aligned-signed的包，但是好像没有7z压缩的。最后只出了3个apk。

**Comment by simpleton** [comment]
对，使用了V2签名的不再用7zip压缩了

**Comment by simpleton** [comment]
@ml0728119 使用1.2.8之后还有问题么？

**Comment by simpleton** [comment]
@ml0728119 这里先关闭了，遇到问题后请重新打开。

**Comment by simpleton** [comment]
@ml0728119 确认一下你的签名使用的算法是否填写正确，如果没有特别配置，请不要设置`digestalg `
