### ISSUE TITLE
混淆之后，apk从12M到了15M，怎么变大了呢？？

### ISSUE THREAD

**Issue by cby0310** [shwenzhang/AndResGuard#207]
![qq 20171104104240](https://user-images.githubusercontent.com/6885903/32401606-3f251f0c-c14d-11e7-84be-1b395c851d0e.png)

**Comment by cby0310** [comment]
使用的是androidstudio3.0，classpath配置如下：
          classpath 'com.android.tools.build:gradle:3.0.0'
          classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.8-RC1'
andResGuard使用的是默认的，没有做改动

**Comment by simpleton** [comment]
具体看下是哪里大呢

**Comment by cby0310** [comment]
上面的截图就是对比结果啊     具体就是classes.dex和classes2.dex增大了

**Comment by simpleton** [comment]
不好意思，email收到的是没有图的。AndResGuard应该只会对资源进行更改，dex是不会更改的。你的编译过程中还有其他步骤会影响dex么？

**Comment by simpleton** [comment]
@cby0310 可以尝试升级到1.2.8之后确认还有问题么？ 如果问题依旧存在，可以发原始包给我。我帮你debug下。

**Comment by simpleton** [comment]
这里先关闭了，如果有进一步的问题请重新打开
