### ISSUE TITLE
write custom gradle task 

### ISSUE THREAD

**Issue by rexi1r** [shwenzhang/AndResGuard#209]
hi.
I have two flavors like (resguardOneRelease, resguardTwoRelease), I want to write some Gradle task to run both in sequence. but any attempt to defeat. 

how can I do something like this?

**Comment by simpleton** [comment]
`./gradlew  resguardOneRelease resguardTwoRelease` shoud work.
Or u can write a task depends on the tasks which u wanna running.
Or just run `./gradlew resguardRelease` for all tasks which buildType is
Release
