### ISSUE TITLE
tool_output的AndResGuard-cli-x.y.z.jar仍是1.2.6版本

### ISSUE THREAD

**Issue by alfredkzhong** [shwenzhang/AndResGuard#210]
tool_output的AndResGuard-cli-x.y.z.jar仍是1.2.6版本，这个版本仍未修复7zip后Assets文件夹会产生空文件的问题。因为我们resguard之后还需要对apk作处理，所以最后的7zip是用命令行来完成的。如果有更新计划或者能抽到时间，希望可以更新下tool_output的命令行jar.

**Comment by simpleton** [comment]
是这个错误么？ref #162
