### ISSUE TITLE
V2 签名与 7z 压缩的一些疑问

### ISSUE THREAD

**Issue by NashLegend** [shwenzhang/AndResGuard#212]
可不可以先使用 V1 签名并 7z 压缩输出 apk 后，再使用 V2 签名对 apk 重新签名呢。我在本地跑 demo 试了一下貌似没有问题

**Comment by weinierfei** [comment]
v2重新签名后,apk还是不是7z压缩过的大小?

**Comment by NashLegend** [comment]
@weinierfei 除了签名文件以外，其他是完全一致的

**Comment by simpleton** [comment]
@NashLegend @weinierfei 多谢建议，v2重签是会大一点点，但是比没做过7zip的还是要小。

**Comment by simpleton** [comment]
@NashLegend @weinierfei 可以try一下  1.2.10-DEBUG1，如果手边有API 14 - 16的机器，麻烦帮我测试一下安装，多谢了。

**Comment by weinierfei** [comment]
@simpleton 我们的项目minSdkVersion直接17了,公司里都没有低于17的机器

**Comment by NashLegend** [comment]
@simpleton  我们最低19了:heart_eyes:
