### ISSUE TITLE
白名单的问题

### ISSUE THREAD

**Issue by binbin594738977** [shwenzhang/AndResGuard#213]
当我不知道那些资源是不能混淆的,那么我可不可以设置黑名单,也就是只混淆指定的资源,这样更加安全

**Comment by simpleton** [comment]
可以，但是没有特殊的原因，混淆都是安全的。设计的时候逻辑也是参照ProGuard，当然也欢迎PR

**Comment by binbin594738977** [comment]
我发现微博分享的时候有异常,并且不能混淆rootFile,我找不到原因,所以我希望只混淆掉我自己的资源,但是没有相应的方法!  不过我发现使用通配符和正则表示式这样可以取巧的添加<指定文件的其他文件>([^a])添加白名单,这样达到了添加黑名单效果.

**Comment by simpleton** [comment]
@binbin594738977 
[现有白名单](https://github.com/shwenzhang/AndResGuard/blob/master/doc/white_list.md)

ref #69

**Comment by JianGsHanz** [comment]
怎么只混淆自己项目的资源，不混淆第三方sdk的，找了好多资料都没找到
