### ISSUE TITLE
gradle添加之后图片没有压缩，这是哪里设置错误了么？

### ISSUE THREAD

**Issue by tmexcept** [shwenzhang/AndResGuard#214]
## gradle版本： classpath 'com.android.tools.build:gradle:2.3.3'

能正常打包，打包完成后没有找到final.apk

![image](https://user-images.githubusercontent.com/10299901/33479677-eaddb2ec-d6c8-11e7-83ad-74a7b51eb747.png)
![image](https://user-images.githubusercontent.com/10299901/33479745-3561989c-d6c9-11e7-9f04-09d4e30a51a8.png)

**Comment by simpleton** [comment]
你可以试下1.2.10—DEBUG1，或者使用V1签名

**Comment by tmexcept** [comment]
使用com.tencent.mm:AndResGuard-gradle-plugin:1.2.10-DEBUG1之后，使用v1签名、V2签名图片都没有压缩

**Comment by simpleton** [comment]
你查看的包似乎不对，插件打出来的包不是这么命名的

**Comment by tmexcept** [comment]
是final.apk是么？没有找到生成的final.apk的包

**Comment by simpleton** [comment]
具体查看下log吧

**Comment by simpleton** [comment]
我暂时无法在sample中复现你描述的问题，如仍然存在，请添加复现步骤并重新打开issue
