### ISSUE TITLE
通过反射获取的资源需要加入白名单么？

### ISSUE THREAD

**Issue by EasyLiu-Ly** [shwenzhang/AndResGuard#217]
如下：
![image](https://user-images.githubusercontent.com/15091355/33642143-8bd81e78-da73-11e7-87ff-f1b11dcddba8.png)

![image](https://user-images.githubusercontent.com/15091355/33642150-93bc6c16-da73-11e7-8408-a563053f7808.png)
我发现没有加入白名单也没问题！

**Comment by simpleton** [comment]
这取决于thumbImgStr传入的是什么，如果是混淆前的名字则需要加入白名单。

**Comment by EasyLiu-Ly** [comment]
确实是混淆之前的名字，没有加入白名单也没发现有什么问题，这是怎么回事？
