### ISSUE TITLE
can not find the compress dataresFile

### ISSUE THREAD

**Issue by yaoooo** [shwenzhang/AndResGuard#22]
can not find the compress dataresFile=res/drawable/setup_steps_instruction_circle_shape.xml
can not find res file, you delete it? path: resFile=/Users/yy/AndroidStudioProjects/AndResGuard-master/app-release/temp/res/drawable/setup_steps_instruction_circle_shape.xml
can not find the compress dataresFile=res/drawable/setup_steps_title_circle_shape.xml
can not find res file, you delete it? path: resFile=/Users/yy/AndroidStudioProjects/AndResGuard-master/app-release/temp/res/drawable/setup_steps_title_circle_shape.xml
很多文件找不到，这是为什么呢？

**Comment by shwenzhang** [comment]
这是在resources.arsc找到这个项，但是却没有这个资源文件。

**Comment by yaoooo** [comment]
感谢 我已经找到原因了 因为使用了shrinkResources，导致一些资源被删除
