### ISSUE TITLE
tinker + Andresguard 打patch失败

### ISSUE THREAD

**Issue by hellokugo** [shwenzhang/AndResGuard#223]
tinker + Andresguard打包，执行buildRTinkerPatchRelease打包失败

版本信息：
com.tencent.bugly:tinker-support:1.1.0
com.tencent.mm:AndResGuard-gradle-plugin:1.2.10
com.android.tools.build:gradle:3.1.0-alpha06

错误信息：
* What went wrong:
Execution failed for task ':app:resguardUseApk'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class java.lang.String]
  	[class java.net.URI]

**Comment by simpleton** [comment]
你应该提到tinker或者bugly那边，这个task（`buildRTinkerPatchRelease `）不是AndResGuard插入的
