### ISSUE TITLE
可否手动执行resguard？

### ISSUE THREAD

**Issue by coolegos** [shwenzhang/AndResGuard#228]
目前项目多渠道打包使用渠道信息放在apk的zip comment的做法，所以流程是生成资源混淆的apk 以后再做多渠道打包的过程。
有一个问题，目前项目打包方式已经比较复杂了，因此不能执行resguardRelease(`task.dependsOn "assemble${variantName}"`)来打包。
想问一下能不能手动在`variant.assemble.doLast {}`中去处理resguard？？

**Comment by simpleton** [comment]
@coolegos  感觉直接让多渠道包的task依赖resguard[xxx]即可。如果要自己来实现可以参考plugin里的代码。

**Comment by coolegos** [comment]
```
android {
    defaultConfig {
        applicationVariants.all { variant ->
            variant.assemble.doLast {
                tasks.findAll { task ->
                    if (task.name.startsWith('resguard')) {
                        //doSomething
                    }
                }
            }
        }
    }
}
```
最后是按照你说的做的，执行完resguard 做一些特殊操作。写的比较low。
