### ISSUE TITLE
AndResGuard is promoting some bad practices

### ISSUE THREAD

**Issue by wojtek-kalicinski** [shwenzhang/AndResGuard#233]
I like the idea of having a toolbox that lets you further optimize your APK, but some of the "optimizations" offered by AndResGuard go against good practices:

1) there are good reasons why some files in the APK are not compressed, such as resources.arsc or native libraries (*.so/dll), so they can be read directly from APK at runtime. By offering/suggesting adding compression to them you in fact prevent optimization and degrade the experience at runtime. Ideally AndResGuard should not compress resources.arsc or at least add an explanation in the manual of why it's not a good idea.

2) recompressing the APK with 7zip makes little sense for APKs distributed via Play, as it might prevent some optimizations such as File-by-file patches, which greatly reduce download size for updates. Also the initial download from Play is compressed anyway, so this andresguard feature would only affect the APK size on disk and to a small degree. At the very least you shouldn't guide developers who distribute on Play to use 7zip recompression

**Comment by simpleton** [comment]
Totally agree! 

1. I'll disable resource.asrc and native libraries compression by default and show a warning when the developer enable them.

2. I'll turn off the recompressing flag in Readme file and add notes for developers who distribute their APK on GooglePlay. You know, the Play is not available in China mainland. So this flag is still useful for the developers release their APK by themselves or some third-party Store which didn't support patching update.

Feel free to contact me if there's any other harmful behavior.

**Comment by wojtek-kalicinski** [comment]
Awesome, thank you very much for the prompt response!

**Comment by BryanSharp** [comment]
mark this

**Comment by 850636558myj** [comment]
对于发布于Google Play的APP，建议不要使用7Zip压缩，因为这个会导致Google Play的优化Patch算法失效    这个优化算法有什么作用，没了会有什么影响呢？

**Comment by simpleton** [comment]
升级包会变大

**Comment by 850636558myj** [comment]
升级后的包也是我们自己上传的 ，升级包会变大是什么意思呢？   我们上传上去之后，gp还会帮我们压缩一次么？

**Comment by yangpeiyong** [comment]
> 升级后的包也是我们自己上传的 ，升级包会变大是什么意思呢？ 我们上传上去之后，gp还会帮我们压缩一次么？

使用google play升级apk的时候，会比较手机已经安装的apk和play上最新的apk差异，只会下发一个比较小的patch来升级apk。
