### ISSUE TITLE
多Flavor+buildType 构建失效

### ISSUE THREAD

**Issue by sunsteam** [shwenzhang/AndResGuard#236]
hi 我在做一个demo，关于使用AndResGuard+Tinker的，发现flavor>1时，使用 resguardFlavor1Flavor2Release这样的格式，AndResGuard会失效。task显示执行了，任务结果是ok，但实际没有执行，只有原始的apk输出。我以为是配置写错了，倒腾了半天，但最后删掉一个FlavorDimensions就好了。

虽然实际使用很少有这样的情况，发现了还是汇报一下。

**Comment by simpleton** [comment]
我印象好像没有这种语法`resguardFlavor1Flavor2Release` 需要`resguardFlavor1Release resguardFlavor1Release`，如果我搞错了可以随时纠正我。

**Comment by imknown** [comment]
我记得 有一个 10天前 提问的类似 issue, 找不到了, 貌似被 .. 删除了?

**Comment by imknown** [comment]
我记得 有一个 10天前 提问的类似 issue, 找不到了, 貌似被 .. 删除了?

**Comment by sunsteam** [comment]
是我没说完整，应该是2个flavordimensions，对应2组flavor。

定义方式

```
flavorDimensions "category","sell" 

    productFlavors {

        demo{
            dimension "category"
        }
        complete{
            dimension "category"
        }

        free{
            dimension "sell"
        }
        pro{
            dimension "sell"
        }
    }

```

![](https://ws1.sinaimg.cn/large/006tNc79gy1fousi6855pj31kw0r143f.jpg)

**Comment by imknown** [comment]
你的 `flavorDimensions` 用法不正确吧, `Dimensions` 就是为了多维度而生的.
https://developer.android.com/studio/build/build-variants.html?hl=zh-CN#flavor-dimensions

**Comment by sunsteam** [comment]
@imknown 没错啊 ，2个维度一个定义了是演示demo还是开发完成的complete版本，另一个定义了是限制功能的免费试用版free还是需要付费的专业版pro，假如是真实项目，里面的srcDir会有区别的，我这只是demo。

再说这个也不是重点，主要是这个构建任务是合法的，只是内容没有执行。

**Comment by imknown** [comment]
@sunsteam 嗯, 我的错... 看了一眼, 不知道对不对, 感觉好像确实没处理 `flavorDimensions`:

https://github.com/shwenzhang/AndResGuard/blob/develop/AndResGuard-gradle-plugin/src/main/groovy/com/tencent/gradle/BuildInfo.groovy#L15-L22

**Comment by sunsteam** [comment]
@imknown 我觉得应该是AndResguardTask.groovy中的这一段，flavor只取了第一个。 不过我觉得问题不大，实际开发很少这样2个dimension，我发出来也只是为了有人遇到的话能查得到。

```groovy
static isTargetFlavor(variantName, flavors, buildType) {
        if (flavors.size() > 0) {
            String flavor = flavors.get(0).name
            return variantName.equalsIgnoreCase(flavor) || variantName.equalsIgnoreCase([flavor, buildType].join(""))
        }
        return false
    }
```

**Comment by simpleton** [comment]
对，dimens 没有支持。只支持到了buildType 和flavor

**Comment by k4dima** [comment]
@sunsteam use AndResGuard-cli-1.2.12.jar from tool_output. It works with multiple flavors.

**Comment by zhangkehu** [comment]
@simpleton 大佬，多维度flavor打包的问题大概时候什么时候更新到gradle的插件里？

**Comment by simpleton** [comment]
Flavor 支持的

**Comment by zhangkehu** [comment]
@simpleton 额，我说的是定义了多个flavorDimensions 就是这个issue里前面几位提到的问题，假如定义了两个dimension：
```
flavorDimensions “product”,"cpuArch"
    productA{
        dimension "product"
    }
    productB{
        dimension "product"
    }

    amrV7{
        dimension "cpuArch"
    }
    x86{
        dimension "cpuArch"
    }
```
假如定义了上面的两个维度的flavor，现在编译命令如下：gradlew resguardProductAX86Release
这样的命令AndResGuard并不能将assemble出来的apk重新打包压缩资源，assemble结束AndResGuard里的task很快就执行完了（应该是没有正确执行直接结束了）。我用的版本：
classpath "com.tencent.mm:AndResGuard-gradle-plugin:1.2.12"

**Comment by zhangkehu** [comment]
@simpleton 我用图说明一下哈
![4 3 pv81s2 jk6 5oxv w](https://user-images.githubusercontent.com/9359883/38847229-282e64e0-4233-11e8-8939-d7a8dc1539ff.png)

**Comment by jokermonn** [comment]
这个 issue 应该算是在 #301 修复了吧

**Comment by Yuiffy** [comment]
经验证已修复。
我用1.2.15版本遇到这个问题，更到1.2.17版本就没有了。
