### ISSUE TITLE
为什么压缩了以后，包反而变大了呢？

### ISSUE THREAD

**Issue by luhaikong** [shwenzhang/AndResGuard#239]
[https://github.com/shwenzhang/AndResGuard/blob/master/doc/how_to_work.zh-cn.md]() 这个页面上的，【Androd资源混淆工具的耗时与效果】目录下的第二项内容，【compres参数(下文有详细描述，是否压缩某些资源)对安装包大小的影响】。

**Comment by simpleton** [comment]
具体查看2个包增大的原因吧, 可以用as的工具diff下apk.

**Comment by yuger** [comment]
借楼一用，我就不新开issue了
如果使用了firebase的[fireStore](https://firebase.google.cn/docs/firestore), 会出现崩溃，
需要在whitelist中添加`R.string.project_id`,我花了三个小时才定位到问题，请作者添上。

**Comment by simpleton** [comment]
@yuger 多谢报告。
