### ISSUE TITLE
AndroidTest.apk可以被混淆么

### ISSUE THREAD

**Issue by TMLAndroid** [shwenzhang/AndResGuard#240]
设备测试（uiautomator生成的apk）可以被混淆么，怎么混淆呢

**Comment by simpleton** [comment]
没有理解你的问题，APK为什么会被测试设备生成？

**Comment by TMLAndroid** [comment]
可能我描述的不是很清楚，就是ui自动测试框架（uiautomator）生成的apk可以对其进行混淆么，生成apk位置如下
 
![Uploading WX20180303-16474
<img width="481" alt="wx20180303-164746 2x" src="https://user-images.githubusercontent.com/15682442/36932387-2f094828-1f03-11e8-8492-a9a4a5b01e9a.png">
6@2x.png…]()

**Comment by imknown** [comment]
你的目的仅仅是想混淆, 还是混淆完了顺便安装 还是 别的啥子..

**Comment by TMLAndroid** [comment]
我现在已经可以对其进行了签名和打包，安装都ok了，就是配置的混淆规则总是不生效，反编译出来全局变量还是不变，没有用"abc....."代替，我不清楚是我混淆规则写错了还是官方本身不支持androidTest.apk的混淆，所以来问问这里的大佬
下面是我gradle.build文件
```gradle
 buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            //proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            testProguardFile 'proguard-test-rules.pro'
        }

    }


    testBuildType "release"
```
这个是我混淆文件proguard-test-rules.pro
```gradle
-ignorewarnings
-keepattributes *Annotation*

-dontnote junit.framework.**
-dontnote junit.runner.**

-dontwarn android.test.**
-dontwarn android.support.test.**
-dontwarn org.junit.**
-dontwarn org.hamcrest.**
-dontwarn com.squareup.javawriter.JavaWriter
```
烦请大佬指点迷经

**Comment by simpleton** [comment]
AndResGuard只针对资源混淆，看你的描述是在做proguard。

**Comment by imknown** [comment]
看懵逼了..

**Comment by TMLAndroid** [comment]
是的，不是针对资源的，是代码的混淆，有这方面相关的疑问，所以咨询咨询一下 @simpleton

**Comment by TMLAndroid** [comment]
哥，你知道么 @imknown

**Comment by imknown** [comment]
@TMLAndroid 左转.. Google ProGuard... 很多资料
