### ISSUE TITLE
远程主机关闭了一个现有连接

### ISSUE THREAD

**Issue by BrightVan** [shwenzhang/AndResGuard#242]
之前一直都没问题的，1.2.11版本。
刚才打包就一直报这个错。
开了V2签名，关了也没用。
换成1.2.12版本也没有。
重启AS也没用。
完全不知道什么情况
如果V2签名开启，还会同时出现下面的提示：
Warning:Console uses unknown character encoding: cp0. Using GBK instead

**Comment by simpleton** [comment]
感觉你没有描述清楚问题，请具体描述一下一下问题。
出问题的版本：
没有问题的版本：
出问题版本完整的log(--stacktrace):

**Comment by BrightVan** [comment]
3月9号用都没有问题，用的版本一直是1.2.11，也开了V2签名，没有任何问题。
昨天就突然报了上面的错误。然后我去github看了下，有新版本，用了1.2.12，还是有错。
然后我有尝试关闭V2，也没有用。现在就是完全不能根据这个错误提示找到原因。以前如果生成apk目录被打开，才可能报“远程主机关闭了一个现有连接”这种错误，关闭就没问题了。

错误信息如下：
Information:Gradle tasks [resguardRelease]
Error:Failed to complete Gradle execution.

Cause:
远程主机强迫关闭了一个现有的连接。

//下面的部分之前正常时也一直都有，关系不大，主要是jar包编译版本旧
Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.samsung.android.sdk.pass.d) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.samsung.android.sdk.pass.a) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.samsung.android.sdk.pass.c) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.samsung.android.sdk.pass.e) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.samsung.android.sdk.pass.b) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is *not* an inner class.

Warning:Console uses unknown character encoding: cp0. Using GBK instead

**Comment by simpleton** [comment]
这个都是warnings，你可以重新run task，添加--info

**Comment by BrightVan** [comment]
按照上面的提示信息（“ (文件名、目录名或卷标语法不正确。)”），问题已解决。
