### ISSUE TITLE
glide加载图片然后进行毛玻璃处理失败

### ISSUE THREAD

**Issue by fableyjg** [shwenzhang/AndResGuard#243]
请问，用这个工具压缩release包后，glide加载图片然后毛玻璃处理失败是什么原因啊？
在glide中用了自定义的transform，崩溃指向了
RenderScript rs = RenderScript.create(mContext);
这一行。
谢谢！

**Comment by simpleton** [comment]
提供的信息太少了，无法帮你诊断问题。
