### ISSUE TITLE
反馈个问题

### ISSUE THREAD

**Issue by zhangkehu** [shwenzhang/AndResGuard#245]
错误日志：

> android.content.res.Resources$NotFoundException:File r/a1/a.png from drawable resource ID #0x7f0b0000
> --
> 2 android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:356)
> 3 ......
> 4 Caused by:
> 5 java.io.FileNotFoundException:This file can not be opened as a file descriptor; it is probably compressed
> 6 android.content.res.AssetManager.openNonAssetFdNative(Native Method)
> 7 android.content.res.AssetManager.openNonAssetFd(AssetManager.java:795)
> 8 android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:354)
> 9 android.content.res.Resources.openRawResourceFd(Resources.java:1330)
> 10 com.umeng.socialize.media.UMImage$ResConvertor.asFile(UMImage.java:546)
> 11 com.umeng.socialize.media.UMImage.asFileImage(UMImage.java:218)
> 12 com.umeng.socialize.media.WeiXinShareContent.buildMediaMessage(WeiXinShareContent.java:412)
> 13 com.umeng.socialize.media.WeiXinShareContent.buildTextImageParams(WeiXinShareContent.java:393)
> 14 com.umeng.socialize.media.WeiXinShareContent.getWxMediaMessage(WeiXinShareContent.java:118)
> 15 com.umeng.socialize.handler.UMWXHandler.shareTo(UMWXHandler.java:453)
> 16 com.umeng.socialize.handler.UMWXHandler.share(UMWXHandler.java:443)
> 17 com.umeng.socialize.b.a.a(SocialRouter.java:346)
> 18 com.umeng.socialize.i.a(UMShareAPI.java:173)
> 19 com.umeng.socialize.i.doInBackground(UMShareAPI.java:168)
> 20 com.umeng.socialize.common.QueuedWork$UMAsyncTask$1.run(QueuedWork.java:150)

关于notfound的问题，apk解压开我检查了对应目录，图片是存在的，目录和名字也对的上。
排除代码混淆的问题，用assebleXXRelease编译出来的包运行正常，用resguardXXRelease编译出来的会崩溃。另外用resguard编译的时候我keeproot 设置成true，whiteList里加入"R.drawable.*",也不行。

PS：资源是放在aar的一个模块里的，感觉跟这个关系比较大，以前资源在主模块app里的时候没问题。

**Comment by simpleton** [comment]
可以加入白名单，从call stack 看，这个资源是umeng 加载的

**Comment by zhangkehu** [comment]
啊，感觉不是白名单的问题。keeproot 是true，白名单加了R.drawable.*，这样全部都不混淆。这种配置也不行。以前可以，现在不行了是因为现在这个资源在我的一个library里。

**Comment by zhangkehu** [comment]
我现在不传id了，直接给友盟传个bitmap进去，暂时规避了，我也不想搞这个问题了，弄一天了。
PS：友盟的sdk很老了，传个mipmap的id进去直接废了，后来改成drawable，发现可以了，然后resguard之后发现还是那里挂。
