### ISSUE TITLE
日志打印敏感信息

### ISSUE THREAD

**Issue by panchangpeng** [shwenzhang/AndResGuard#253]
https://github.com/shwenzhang/AndResGuard/blob/d5745628c962eea311dcb45f363cd40a22389923/AndResGuard-core/src/main/java/com/tencent/mm/androlib/ResourceApkBuilder.java#L250

这个应该是忘记注释了吧，signWithV2sign有注释,v1没有注释。jenkins集成时日志把密码打印出来了。

**Comment by simpleton** [comment]
收到，多谢指出。我晚些时候发版fix
