### ISSUE TITLE
`Failed to parse /data/app/vmdl1987242670.tmp/base.apk: AndroidManifest.xml` on Windows only

### ISSUE THREAD

**Issue by imknown** [shwenzhang/AndResGuard#254]
Windows raises the error below but Linux **DOES NOT**.
```
adb: failed to install CityMngSystem-1.3.7(23)-20180516-RRPA-YiPaiV137R_7zip_aligned_signed.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1987242670.tmp/base.apk: AndroidManifest.xml]
```
------
- AndResGuard: 1.2.13
- OS: Windows 7/10 64bit
- Android Studio: 3.1.2
- Android Studio Plugin for Gradle: 3.1.2
- Gradle: 4.7-all

**Comment by imknown** [comment]
@simpleton Windows-generated App cannot be installed on real phones, and there is no dir like `.expo/android-apk-cache`.

---

The `assembleRelease` works well but the `resguardRelease` not. Maybe the issue on `SevenZip`?

**Comment by simpleton** [comment]
I'm not sure. Maybe u can disable SevenZip flag for debuging.

**Comment by imknown** [comment]
@simpleton `use7zip = false` works.

**Comment by shmet206** [comment]
hi, can someone please help me with this issue I'm having when trying to install an android apk file using adb. Everything was working and just stopped working recently. I have no clue what changed.

Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl1311252415.tmp/base.apk]

**Comment by imknown** [comment]
@shmet206 Need more log.

**Comment by bpstelios10** [comment]
i usually just clean the project
```
"clean:android": "cd android && ./gradlew clean && cd ../",
"clean:ios": "cd ios && xcodebuild clean && cd ../",
"clean": "npm run clean:android && npm run clean:ios"
```

**Comment by satyammca** [comment]
> 

We are also getting same error while installing via adb install command - adb: failed to install xxxx.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl1706283596.tmp/base.apk: AndroidManifest.xml]
