### ISSUE TITLE
发现个和华为推送相关的问题

### ISSUE THREAD

**Issue by zhangkehu** [shwenzhang/AndResGuard#255]
因为华为推送的sdk中有使用getResources().getIdentifier()，所以他用到的资源自然是需要keep住的。例如：hms_update_title这个字符串，可把我搞坏了，整了一天才想起来这里有问题，还一直以为华为推送sdk有bug。和华为的小哥折腾了一天，哎，浪费人家时间了。不知道还有没有别的资源需要keep的，感觉不太敢继续用AndResGuard打包了。不知道各位朋友能否长期维护一下常见sdk需要keep的资源？感激万分。
或者AndResGuard能否做到对Resource类的getIndentifier方法调用处也keep？

**Comment by pihat** [comment]
"R.string.hms*",
            "R.string.connect_server_fail_prompt_toast",
            "R.string.getting_message_fail_prompt_toast",
            "R.string.no_available_network_prompt_toast",
            "R.string.third_app_*",
            "R.string.upsdk_*",
            "R.layout.hms*",
            "R.layout.upsdk_*",
            "R.drawable.upsdk*",
            "R.color.upsdk*",
            "R.dimen.upsdk*",
            "R.style.upsdk*"

可以参考下，Android7.0及以上和 Android7.0以下机型的升级弹窗是不一样的，建议也测试

**Comment by zhangkehu** [comment]
赞，这种写法还真可行，不过我决定放弃AndResGuard打包了，我怕以后其他的sdk遇到类似的问题。

**Comment by zhangkehu** [comment]
那天AndResGuard对getIndentifier调用的资源也能keep住的话就重新启用 )^_^(
