### ISSUE TITLE
Pro-gaurd rules

### ISSUE THREAD

**Issue by 24Lathiya** [shwenzhang/AndResGuard#258]
Please let me know pro-gaurd rules for your library. got many more warning during signed apk.

Information:Gradle tasks [:app:assembleRelease]
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.ContentInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.util.ObjectIdentifier
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.x509.AlgorithmId
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.util.ObjectIdentifier
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning:com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning:there were 50 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Information:BUILD FAILED in 6s
Error:Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.ContentInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.ContentInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.ContentInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.X500Name
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeSigner: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.util.ObjectIdentifier
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.x509.AlgorithmId
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.util.ObjectIdentifier
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.PKCS7
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: com.android.apksig.internal.apk.v1.V1SchemeVerifier$Signer: can't find referenced class sun.security.pkcs.SignerInfo
Warning: there were 50 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> Job failed, see logs for details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Information:1 error
Information:35 warnings
Information:See complete output in console

**Comment by simpleton** [comment]
This library never compiles any codes to your APK. So there should not be any compatibility issue with Proguard.
