### ISSUE TITLE
换肤的话有什么好的思路？

### ISSUE THREAD

**Issue by Neacy** [shwenzhang/AndResGuard#265]

**Comment by Neacy** [comment]
@simpleton 是这样的，因为AndResGuard会把资源混淆了<假设是R.color.blue会被混淆成a.b.c>   而皮肤包中的资源仍然是R.color.blue   这样子切换皮肤就找不到资源了。

**Comment by simpleton** [comment]
感觉简单处理的话，就使用白名单机制。

如果还是希望可以变短路径，可以按res_mapping来重命名皮肤包资源的名字。
