### ISSUE TITLE
如何使用utf-16编码去压缩resource.arsc

### ISSUE THREAD

**Issue by anAngryAnt** [shwenzhang/AndResGuard#267]
如题

**Comment by simpleton** [comment]
[It appears that the size can be very large if you target minSdkVersion < 7 as strings were stored as UTF-16 then. However if your minSdkVersion is >= 7, it should use UTF-8 which is notably smaller.](https://stackoverflow.com/questions/23260194/why-dont-compress-resources-arsc-in-apk-files)
