### ISSUE TITLE
基于AndResGuard如何实现资源加密

### ISSUE THREAD

**Issue by 1074736711** [shwenzhang/AndResGuard#269]
因为项目需要，希望能够基于AndResGuard做资源加密，我知道AndResGuard的原理是支持的。想问下又没有已经实现了的，或者有没有同学能够给些建议，谢谢。

**Comment by shwenzhang** [comment]
当前AndResGuard只做了资源混淆，要做加密的做法应该不太一样。可以参考一些加固厂商的方案
