### ISSUE TITLE
编译时混淆无法成功No signature of method...

### ISSUE THREAD

**Issue by DaiXiaojie** [shwenzhang/AndResGuard#270]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:resguardProductRelease'.
> No signature of method: static com.tencent.mm.resourceproguard.Main.gradleRun() is applicable for argument types: (com.tencent.mm.resourceproguard.InputParam) values: [com.tencent.mm.resourceproguard.InputParam@514428d1]

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by simpleton** [comment]
可否提供一下完整的callstack和运行版本？

**Comment by DaiXiaojie** [comment]
@simpleton 
已经搞定了，是由于我们引入的一个sdk也引入了你们jar包导致的，谢谢。
