### ISSUE TITLE
Could  not Parse string apk

### ISSUE THREAD

**Issue by Th3CracKed** [shwenzhang/AndResGuard#276]
i added ressources where i use getIdentifier() to WhiteList, the build ended successfully but the apk don't work i have this error 
![capture](https://user-images.githubusercontent.com/10481816/44940737-826be000-ad8a-11e8-9d34-4f7cd797aa3a.PNG)

**Comment by simpleton** [comment]
Can you send me more detail about this issue? or you can send me the problematic APK

**Comment by imknown** [comment]
Is it the same as #254 ?

**Comment by Th3CracKed** [comment]
duplicated sorry
