### ISSUE TITLE
可以更新一下jar文件吗？

### ISSUE THREAD

**Issue by qianzui** [shwenzhang/AndResGuard#283]
我们项目是在打包脚本中直接使用jar文件命令行中处理apk的，可以同步更新一下最新版的jar吗？

多谢啦！

**Comment by qianzui** [comment]
AndResGuard-cli-1.2.12.jar

jar文件还是1.2.12的啊

**Comment by simpleton** [comment]
commit还在develop分支，你可以切换一下分支。

**Comment by yuger** [comment]
> 嗯，看到了。和我本地编译出来的大小是一样的，比1.2.12大不少，我还以为是我编译的有什么问题。多谢啦！

请问你怎么编译出.jar的，我当时也是没找到1.2.15版本，想自己编译一个，结果不知道用Android Studio怎么编译出来。

**Comment by qianzui** [comment]
> > 嗯，看到了。和我本地编译出来的大小是一样的，比1.2.12大不少，我还以为是我编译的有什么问题。多谢啦！
> 
> 请问你怎么编译出.jar的，我当时也是没找到1.2.15版本，想自己编译一个，结果不知道用Android Studio怎么编译出来。

AndResGuard-cli 的 build.gradle里面有buildJar的task
