### ISSUE TITLE
资源混淆后 pl.droidsonroids.gif:android-gif-drawable展示的动态图变成静态图了，有没有相关whiteList

### ISSUE THREAD

**Issue by tangchengHN** [shwenzhang/AndResGuard#287]
使用assembleDebug和assembleRelease打的包都是正常的，使用rR打的包动态图不能动了，能不能指导下怎么配置？解压apk包，里面还是有相关gif，在pc端打开copy出来得gif资源发现也是正常的gif图，就是打开app的时候没有动画效果了

**Comment by simpleton** [comment]
可否在sample中复现这个问题呢？我这边现在暂时没有足够的信息去debug这个问题。多谢

**Comment by jiyewushen** [comment]
在andResGuard配置中避免压缩gif
```java
    compressFilePattern = [
        "*.png",
        "*.jpg",
        "*.jpeg",
 //       "*.gif",
    ]
```

**Comment by tangchengHN** [comment]
已经避免压缩GIF了，  我混淆后解开apk包  找到对应的gif还是正常的，  就是在app中显示出现问题，不能动。
![image](https://user-images.githubusercontent.com/3098505/49582232-48186d00-f98f-11e8-9655-eb2319c4e13e.png)

**Comment by tangchengHN** [comment]
> 在andResGuard配置中避免压缩gif
> 
> ```java
>     compressFilePattern = [
>         "*.png",
>         "*.jpg",
>         "*.jpeg",
>  //       "*.gif",
>     ]
> ```



> 在andResGuard配置中避免压缩gif
> 
> ```java
>     compressFilePattern = [
>         "*.png",
>         "*.jpg",
>         "*.jpeg",
>  //       "*.gif",
>     ]
> ```

这个方法试过还是没用，看我下面说的

**Comment by tangchengHN** [comment]
> 在andResGuard配置中避免压缩gif
> 
> ```java
>     compressFilePattern = [
>         "*.png",
>         "*.jpg",
>         "*.jpeg",
>  //       "*.gif",
>     ]
> ```

这个方法还是没用，看我上面回复的

**Comment by jiyewushen** [comment]
RN开发有其特点，我未使用过它，这种方式仅供参考。~~使用`android-gif-drawable`时，同样不显示动图，报错信息[#259](https://github.com/shwenzhang/AndResGuard/issues/259)，避免压缩Gif可以解决。~~

**Comment by tangchengHN** [comment]
我更新到1.2.15版本后打包发现正常了   辛苦各位了
