### ISSUE TITLE
资源加载问题

### ISSUE THREAD

**Issue by jayronlou** [shwenzhang/AndResGuard#30]
资源混淆之后，apk是如何加载的呢？

**Comment by simpleton** [comment]
还是正常的安装，如果启动有问题可以直接将crash log贴出来，我们看一下

**Comment by jayronlou** [comment]
https://github.com/cundong/SmartAppUpdates
结合这种增量更新优美与问题

**Comment by jayronlou** [comment]
https://github.com/cundong/SmartAppUpdates
结合这种增量更新有没有问题

**Comment by simpleton** [comment]
从原理上讲，应该不会有什么问题。但是我没有测试过，如果在使用中有问题请提issue。这里先close了。
