### ISSUE TITLE
关于zipalign和安装包体积该选哪个？

### ISSUE THREAD

**Issue by ryanlijianchang** [shwenzhang/AndResGuard#300]
我想说下为什么安卓默认png等资源不压缩打包，首先在zipalign的源码里面有句判断代码，如果资源被压缩过，就跳过，否则进行4k对齐。另外在aapt(印象中应该是)的源码中，定义了个字符串数组，用于存放那些不需要压缩的文件类型后缀，谷歌这么做自然有它的用意。如果图片都压缩了，zipalign就等于完全没用，zipalign就是为了资源文件能映射到内存中，如果压缩过就没法直接映射了。最后关于zipalign和安装包体积该选哪个我也不好说。

**Comment by simpleton** [comment]
这取决于你的需求，google假设所有app都要经过google play分发，但这在国内显然不是实际情况。可以参考一下这个issue中的讨论 #233
