### ISSUE TITLE
WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.

### ISSUE THREAD

**Issue by gitgiggity** [shwenzhang/AndResGuard#306]
I get the following warning, when using AndResGuard.

> WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'.
> It will be removed at the end of 2019.

```
Environment:
Android Studio: 3.3.0
Gradle: 4.10.1
com.tencent.mm:AndResGuard-gradle-plugin:1.2.15
```

**Comment by imknown** [comment]
duplicated #304

**Comment by duanyitao** [comment]
+1
