### ISSUE TITLE
编译日志输出敏感信息

### ISSUE THREAD

**Issue by Trumeet** [shwenzhang/AndResGuard#311]
同 #253 ，但我看了下代码，似乎只禁用了 V1 签名的 `dumpParams`，而不是 V2，但我的项目仅启用了 V2 签名。

V2 签名暴露密码： https://github.com/shwenzhang/AndResGuard/blob/ce17502da508579b8974979963becac3e2b7f41c/AndResGuard-core/src/main/java/com/tencent/mm/androlib/ResourceApkBuilder.java#L230

V1 注释掉了：
https://github.com/shwenzhang/AndResGuard/blob/ce17502da508579b8974979963becac3e2b7f41c/AndResGuard-core/src/main/java/com/tencent/mm/androlib/ResourceApkBuilder.java#L258

导致效果如图：
![暴露签名密码等敏感信息](https://i.loli.net/2019/03/01/5c78bf248c0a4.jpg)

**Comment by simpleton** [comment]
@Trumeet 多谢指出问题，可以先使用[`1.2.16-DEBUG`](https://bintray.com/wemobiledev/maven/com.tencent.mm%3AAndResGuard-gradle-plugin/1.2.16-DEBUG)的版本。我随后会发正式的版本
