### ISSUE TITLE
关于签名方面的疑问

### ISSUE THREAD

**Issue by Caij** [shwenzhang/AndResGuard#312]
查看了源码，发现签名是引入apksig的包使用java代码进行签名。 有个疑问就是为什么不用build tool中使用jar命令方式签名，这样也可以在更新sdk的时候使用最新的sign， 是有什么坑吗？  对齐那部分是通过命令完成的。

**Comment by simpleton** [comment]
也是OK的，印象当时引入v2签名的时候的官方sdk没有继承，所以就自己引入了代码。后续会除去这块
