### ISSUE TITLE
WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'. It will be removed at the end of 2019. For more information, see https://d.android.com/r/tools/task-configuration-avoidance.

### ISSUE THREAD

**Issue by wdikiz** [shwenzhang/AndResGuard#317]
I get this error when i add Adresguard 1.2.5 it happen with the version above 3.2.1 of Android gradle plugin.

WARNING: API 'variantOutput.getPackageApplication()' is obsolete and has been replaced with 'variant.getPackageApplicationProvider()'. It will be removed at the end of 2019. For more information, see https://d.android.com/r/tools/task-configuration-avoidance

**Comment by imknown** [comment]
Do NOT duplicated threads.

**Comment by simpleton** [comment]
duplicated.
