### ISSUE TITLE
通过插件的话怎么手动设置zipalign？

### ISSUE THREAD

**Issue by pengwei1024** [shwenzhang/AndResGuard#32]
为zipalign设置了环境变量，但是报错java.io.IOException: Cannot run program "zipalign": error=2, No such file or directory，该怎么手动设置zipalign？在config.xml可以设置？

**Comment by simpleton** [comment]
可以增加到path里，你使用的是gradle的插件么？ 我下个版本会增加一个参数来配置zipalign的path.

**Comment by brucetoo** [comment]
使用gradle插件 报错 
```java
  java.io.IOException: Cannot run program "zipalign": error=2
```
zipalign 环境变量已加，有什么解决方案？谢谢

**Comment by simpleton** [comment]
@brucetoo @pengwei1024 由于大家启动as基本不会带user目录下的环境变量，这里我更新了下，把这种依赖环境变量的参数都配置在`build.gradle`里了，可以参照1.1.1的readme增加以下zipAlign的路径。麻烦验证下

**Comment by brucetoo** [comment]
OK 我马上试试.等下反馈

**Comment by brucetoo** [comment]
Windows版本下 
zipalign路径 
```groovy
zipAlignPath = {"D:\\AndroidSDK\\build-tools\\22.0.1\\zipalign.exe"}
```
报错 
```java 
java.io.IOException: Cannot run program "build_9b386v6dc7ib74u2x7rhdgcm2$_run_closure2_closure7_closure14@60c6a8e2": CreateProcess error=2, ?????????
```

是否是路径不对啊？

**Comment by brucetoo** [comment]
换成 “ / ” 也同样问题

**Comment by simpleton** [comment]
不用增加{}
直接写string即可，我改一下readme，可能有点让人混淆。
例如：
`zipAlignPath = '/Users/sun/Library/Android/sdk/build-tools/21.1.1/zipalign'`

**Comment by brucetoo** [comment]
非常感谢 
```java
BUILD SUCCESSFUL

Total time: 1 mins 1.31 secs
```

**Comment by simpleton** [comment]
不客气，这里这个issue我关闭了，有其他问题随时反馈。

**Comment by doujinhai123** [comment]
ipaligning apk: D:\AndResGuard\tool_output\input\input_signed.apk, exists:true
java.io.IOException: Cannot run program "zipalign": CreateProcess error=2, ϵͳ▒Ҳ▒                                                                                                    ▒▒ָ▒▒▒▒▒ļ▒▒▒
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.tencent.mm.util.Utils.runCmd(Utils.java:53)

**Comment by doujinhai123** [comment]
嗨，使用命令行的方式运行程序，总是报错啊

**Comment by simpleton** [comment]
加入环境变量即可

**Comment by Cangol** [comment]
> 不用增加{}
> 直接写string即可，我改一下readme，可能有点让人混淆。
> 例如：
> `zipAlignPath = '/Users/sun/Library/Android/sdk/build-tools/21.1.1/zipalign'`
这个加到那个文件里
