### ISSUE TITLE
Apktool繞過AndResGuard保護

### ISSUE THREAD

**Issue by ICommandMachinesObey** [shwenzhang/AndResGuard#342]
新版本的Apktool繞過AndResGuard保護，在Apktool v2.4.0上進行了測試

**Comment by simpleton** [comment]
AndResGuard设计不是一个安全工具，更多的是为了减少安装包大小。原先的混淆只是一个附加的功能，这里更多的添加对抗的功能。

**Comment by ICommandMachinesObey** [comment]
但这个名字指的是资源保护
