### ISSUE TITLE
关于合并重复资源功能提个建议

### ISSUE THREAD

**Issue by LittleLiByte** [shwenzhang/AndResGuard#346]
我看了合并后生成的merge_duplicated_res_mapping_xxxx.txt文件，发现不同分辨率文件夹的资源文件全都由第一次扫描出来的相同hash值的文件代替了，感觉这个做法有优化的空间。
比如先扫描到res/drawable-mdpi/xxx.png，而后在xhpdi，xxhpdi的相同文件都会被移除，最终都使用res/drawable-mdpi/xxx.png。
所以能否添加个配置项，在有重复项时，可以指定保留哪一个分辨率文件夹下的资源？

**Comment by ysbing** [comment]
@LittleLiByte 这个没关系的，在resources.arsc里面有对不同分辨率做了区分，只是替换了其索引的文件。

**Comment by LittleLiByte** [comment]
> 是替换了其索引的文

soga,了解了
