### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ThinkWYP** [shwenzhang/AndResGuard#36]
如何通过As里面的命令行，生成一个混淆的apk啊
运行andresguard/generate的gradle任务，可以得到资源混淆的安装包
这句没看懂

**Comment by simpleton** [comment]
可以在命令行运行`./gradlew generate`。

或者在as的gradle task里找`andresguard`里的`generate`

**Comment by ThinkWYP** [comment]
@simpleton 可以了，谢谢，还有一个问题，就是zipAlignPath的路径，然后每个人用这个都要设置一次路径吗

**Comment by simpleton** [comment]
不设会直接用command line里的`zipalign`。通过issue 后来发现大家基本都不传command line的环境变量到AS，所以就在build.gradle里设了。如果要在team里推，可以把这个值放到local.properties，每个人用不同的值。
