### ISSUE TITLE
1.2.17插件无法下载

### ISSUE THREAD

**Issue by shouzhong** [shwenzhang/AndResGuard#360]

**Comment by simpleton** [comment]
Log是什么？如果无法现在请先检查一下自己的网络设置，我看Jcenter已经有1.2.17的包了

https://bintray.com/wemobiledev/maven/com.tencent.mm:AndResGuard-gradle-plugin/1.2.17
https://bintray.com/wemobiledev/maven/com.tencent.mm%3AAndResGuard-core/1.2.17

**Comment by shouzhong** [comment]
解决了，可能我用了阿里的库，那边资源没同步过来，把jcenter加进去就好了
