### ISSUE TITLE
能不能增加参数，指定输入apk的名称，我们使用了apply plugin: 'multi_channel_plugin'插件

### ISSUE THREAD

**Issue by coolstar1204** [shwenzhang/AndResGuard#365]
项目脚本使用apply plugin: 'multi_channel_plugin'插件进行多渠道打包。所以编译时，AndResGuard总是在multichannel后面工作，这时就提示找不到app-release.apk,因为改名了。能增加一个参数或设置执行顺序就好了

**Comment by simpleton** [comment]
推荐在multichannel之前做AndResGuard

**Comment by chenfei0928** [comment]
可以使用多渠道包CLI工具，在AndResGuard出混淆包之后对混淆包打多渠道包

例如美团的Walle就提供了CLI工具（不过其官方提供的CLI工具在V3签名更新后GG了，可以使用社区版：https://github.com/Meituan-Dianping/walle/issues/264）
