### ISSUE TITLE
1.2.16 提示找不到,已经加了google()

### ISSUE THREAD

**Issue by xiaobaDev** [shwenzhang/AndResGuard#369]
ERROR: Could not find com.android.tools.build:apksig:3.1.4.
Searched in the following locations:
  - https://jcenter.bintray.com/com/android/tools/build/apksig/3.1.4/apksig-3.1.4.pom
  - https://jcenter.bintray.com/com/android/tools/build/apksig/3.1.4/apksig-3.1.4.jar
Required by:
    project :app > com.tencent.mm:AndResGuard-gradle-plugin:1.2.16 > com.tencent.mm:AndResGuard-core:1.2.16

**Comment by simpleton** [comment]
应该是网络问题
