### ISSUE TITLE
 Could not find property 'release' on SigningConfig container.

### ISSUE THREAD

**Issue by tinybright** [shwenzhang/AndResGuard#38]
Could not find property 'release' on SigningConfig container.

**Comment by simpleton** [comment]
Didn't you set your singingConfig in your `build.gradle` ?
Here is the code snippet:
```groovy
 signingConfigs {
        release {
            storeFile file("../keystore/release.keystore")
            storePassword "testres"
            keyAlias "testres"
            keyPassword "testres"
        }

        debug {
            storeFile file("../keystore/debug.keystore")
        }
    }
```

**Comment by tinybright** [comment]
```
signingConfigs {
        config1 {

        }
 }
```
这个应该是取第一个吧。感觉按名字取不靠谱。

**Comment by pranaysharma** [comment]
I am getting the same error. The regular release is build correctly which I can upload to the play store.
My Gradle file is similar to as suggested at :  [https://github.com/futurice/android-best-practices#gradle-configuration](url)

```
signingConfigs {
    release {
        try {
            storeFile FILE_PATH
            storePassword KEYSTORE_PASSWORD
            keyAlias KEY_ALIAS
            keyPassword KEY_PASSWORD
        }
        catch (ex) {
            throw new InvalidUserDataException("You should define KEYSTORE_PASSWORD and KEY_PASSWORD in gradle.properties.")
        }
    }
}
```

These variables are stored in gradle.properties

**Comment by tinybright** [comment]
You should remove try catch

**Comment by pranaysharma** [comment]
Thankyou again for your reply.
I tried removing the try catch also. Got the below error on console


> :app:generate
>  use7zip = true
>  metaName = META-INF
>  keepRoot = false
>  whiteList = [com.tollmequick.www.parkzap_user.R.drawable.icon, com.tollmequick.www.parkzap_user.R.string.com.crashlytics.*]
>  compressFilePattern = [*.png, *.jpg, *.jpeg, *.gif, resources.arsc]
>  zipAlignPath = /Users/pranay/Library/Android/sdk/build-tools/23.0.2/zipalign
>  7zipPath = /usr/local/bin/7za
>         :app:generate FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:generate'.
> > Could not find property 'release' on SigningConfig container.

**Comment by tinybright** [comment]
Did you rebuild your project?And can you add your cmdline and build.gradle?

**Comment by simpleton** [comment]
@pranaysharma I guess it cause by the order of variable declare. could you put the `andResGuard {...}`  at the bottom of your `build.gradle` file?

**Comment by githubchen001** [comment]
按照你说的修改了还是报这样的错

**Comment by tinybright** [comment]
realase  -> release

**Comment by githubchen001** [comment]
真心太不细心了，就说搞了好久 都不知道  汗

**Comment by zhuangjiahua** [comment]
如果项目要打多个渠道包，每个包对应不同的签名，那该如何设置？

**Comment by simpleton** [comment]
使用多productFlavors就可以了，最新版本已经支持了。
