### ISSUE TITLE
gradle tool 3.5.x以上的版本打包出现签名异常的问题

### ISSUE THREAD

**Issue by Caij** [shwenzhang/AndResGuard#380]
gradle-5.4.1-all
com.android.tools.build:gradle:3.5.0
build tool: 28.0.3

Android Studio 3.5 默认推荐的gradle版本 打包出现签名异常的问题

---------------------------------------------

我将build tool更新到29.0.2后打包出来的apk签名没有问题 可以安装， 但是通过签名命令查看 AndResGuard 打包出来的签名变成v3。

使用assemeRelease打出来的包
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false

resguardRelease 打出来的包
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): true

**Comment by zjn0505** [comment]
确实，从 log 里看到的
> [AndResGuard] buildApk signatureType: SchemaV2
不知道最后为什么会变成 Scheme v3

**Comment by zjn0505** [comment]
https://github.com/shwenzhang/AndResGuard/blob/9e6e36437a96f6ef3afb68dab2c18a06322426a2/AndResGuard-core/src/main/java/apksigner/ApkSignerTool.java#L263-L267

这里 v3 scheme 没有特殊处理，而 ApkSigner.Builder 的 V3 是默认为 true 的。https://android.googlesource.com/platform/tools/apksig/+/refs/heads/master/src/main/java/com/android/apksig/ApkSigner.java#959
```
private boolean mV3SigningEnabled = true;
```

**Comment by zicen** [comment]
我也遇到了这个问题。现在资源混淆后 walle 去打包的时候会报错 `app-release.apk has no v2 signature in Apk Signing Block!`。有什么解决方案吗？

**Comment by zicen** [comment]
可以暂时回退到 3.4.1 打包

**Comment by UltramanTIGA** [comment]
这个问题还没解决吗，最新的gradle tool: 4.0.1和gradle 6.1.1依然存在此问题

**Comment by zhangwanggit** [comment]
请问问题解决了没

> 我也遇到了这个问题。现在资源混淆后 walle 去打包的时候会报错 `app-release.apk has no v2 signature in Apk Signing Block!`。有什么解决方案吗？

请问现在有解决办法了没

**Comment by hfbi360** [comment]
> 请问问题解决了没
> 
> > 我也遇到了这个问题。现在资源混淆后 walle 去打包的时候会报错 `app-release.apk has no v2 signature in Apk Signing Block!`。有什么解决方案吗？
> 
> 请问现在有解决办法了没

最新版问题依旧

**Comment by zhangwanggit** [comment]
@simpleton 什么时候发布1.2.21版本呢

**Comment by simpleton** [comment]
> @simpleton 什么时候发布1.2.21版本呢

已经发布了

**Comment by zhangwanggit** [comment]
> > @simpleton 什么时候发布1.2.21版本呢
> 
> 已经发布了
感谢
但升级到1.2.21 会提示 Minimum supported Gradle version is 6.5。。。。这个只能把gradle升级到最新吗
