### ISSUE TITLE
请教几个使用问题

### ISSUE THREAD

**Issue by 850636558myj** [shwenzhang/AndResGuard#386]
1.zipalign  必须设置么，我没设置会报错
![image](https://user-images.githubusercontent.com/55375404/65370101-dabc9b00-dc87-11e9-9726-4b5bfe99dfba.png)
配置完了就可以
![image](https://user-images.githubusercontent.com/55375404/65370108-f45de280-dc87-11e9-9787-ced5e7c82f67.png)

2.zipalign这个有没有配置，有什么作用?
3. 生成的apk有2个，output_signed_aligned.apk   ,output_signed.apk,这2个分别有什么区别，差距1 -2k

**Comment by simpleton** [comment]
这个是字节对齐，对齐的APK会有更好的性能。

**Comment by 850636558myj** [comment]
那第三个问题，区别是不是就是一个有经过align对齐的，后面有这个结尾的就是经过他对齐过的是吗？

**Comment by 850636558myj** [comment]
android推荐经过align对齐，但是有可能出现apk无法安装的情况，请问微信遇到过吗

**Comment by 850636558myj** [comment]
@simpleton
