### ISSUE TITLE
建议添加不混淆resources.arsc中资源名称功能，既不用添加白名单配置

### ISSUE THREAD

**Issue by huopochuan** [shwenzhang/AndResGuard#388]
建议添加不混淆resources.arsc中资源名称功能，既不用添加白名单配置

**Comment by simpleton** [comment]
没理解这个需求的点。。。

**Comment by huopochuan** [comment]
mContext.getResources().getIdentifier()对于使用该方式获取资源id,因为我们混淆了资源名称，所以要添加白名单配置，但是对于大工程而言，添加白名单不会一步到位，所以不启用混淆resources.arsc中资源名称，从而不需要添加白名单。不知道有没有说明白。。。

**Comment by ysbing** [comment]
是说不混淆名称，只混淆路径吧

**Comment by huopochuan** [comment]
对
