### ISSUE TITLE
安装失败 apk内有objectbox so库

### ISSUE THREAD

**Issue by zhaobinsir** [shwenzhang/AndResGuard#391]
[INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2

**Comment by simpleton** [comment]
object box是什么？

**Comment by zhaobinsir** [comment]
是个开源数据库，问题解决了 ，替换了下属性，谢谢您的及时回复






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sim Sun"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午3:57
收件人: "shwenzhang/AndResGuard"<AndResGuard@noreply.github.com&gt;; 
抄送: "吧唧吧唧"<1414074529@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shwenzhang/AndResGuard] 安装失败 apk内有objectbox so库 (#391)




object box是什么？

**Comment by imknown** [comment]
@simpleton 是 GreenBot/GreenDao 搞得一个 类似 realm 的 独立数据库格式.

**Comment by StephenDuan** [comment]
@zhaobinsir 大神，问题怎么解决的，替换了哪个属性？

**Comment by wanwenju** [comment]
https://www.jianshu.com/p/9a75aeb47ab1,看看能不能解决你的问题

**Comment by wanwenju** [comment]
> @zhaobinsir 大神，问题怎么解决的，替换了哪个属性？
看看这个能不能解决你的问题，https://www.jianshu.com/p/9a75aeb47ab1，在清单文件中，application添加这句话        android:usesCleartextTraffic="true"

**Comment by wanwenju** [comment]
> @zhaobinsir 大神，问题怎么解决的，替换了哪个属性？
看看这个能不能解决你的问题，https://www.jianshu.com/p/9a75aeb47ab1，在清单文件中，application添加这句话        android:extractNativeLibs="true"

**Comment by wanwenju** [comment]
> @zhaobinsir 大神，问题怎么解决的，替换了哪个属性？
看看这个能不能解决你的问题，https://www.jianshu.com/p/9a75aeb47ab1
在清单文件中，application添加这句话 android:extractNativeLibs="true"

**Comment by StephenDuan** [comment]
可以，多谢
