### ISSUE TITLE
classpath 'com.android.tools.build:gradle:4.0.0'下variantConfiguration属性找不到

### ISSUE THREAD

**Issue by qinkaiabc** [shwenzhang/AndResGuard#395]
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1-milestone-2-all.zip
classpath 'com.android.tools.build:gradle:4.0.0-alpha07'
工程报错：

No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData

**Comment by whoze** [comment]
今天android studio从3.6.3更新到4.0正式版也是这个错误：
No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData
。这个项目还有人在维护么？

**Comment by amal** [comment]
4.0.0 is now released. Would be great to see compatibility for it

**Comment by simpleton** [comment]
应该在`1.2.18`解决了这个问题，这里我先关闭issue了，有什么问题可以重新打开

------

This issue should be fixed in `1.2.18`, feel free to reopen it if you are still experiencing this issue.
