### ISSUE TITLE
Error: Invalid or corrupt jarfile AndResGuard-cli-1.1.0.jar

### ISSUE THREAD

**Issue by shangzhaohui** [shwenzhang/AndResGuard#40]
hello,使用tool-ouput下面的AndResGuard-cli-1.1.0.jar。报错：Error: Invalid or corrupt jarfile AndResGuard-cli-1.1.0.jar。不知道是什么原因？ 是在mac系统下

**Comment by shwenzhang** [comment]
对于帮助信息的输出之前有问题，最新commit fixed
