### ISSUE TITLE
可以7zip压缩lib/armeabi/*.so文件吗

### ISSUE THREAD

**Issue by 449025693** [shwenzhang/AndResGuard#405]
如题

**Comment by simpleton** [comment]
理论上可以 但需要APP自行解压。

**Comment by 449025693** [comment]
不需要自行解压吧。我看到

**Comment by simpleton** [comment]
我理解错了，我以为你想要二次压缩。不过压缩so并不是google推荐的，这样其实会有更多的copy。

![image](https://user-images.githubusercontent.com/454498/77191232-dbe44e80-6a97-11ea-85a1-1282a38b021e.png)
