### ISSUE TITLE
debug apk包后缀是_signed_7zip_aligned, release apk包后缀是_7zip_aligned_signed

### ISSUE THREAD

**Issue by oncealong** [shwenzhang/AndResGuard#408]
debug apk包后缀是_signed_7zip_aligned, release apk包后缀是_7zip_aligned_signed, 如下图。
AndResGuard版本：classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.2.17'
![image](https://user-images.githubusercontent.com/5340073/78235078-ab29fd80-750a-11ea-8578-8ecfb4b27c7b.png)

请问如何造成的这个情况？后续的打包脚本都需要根据名字分别写了。

**Comment by oncealong** [comment]
发现了，是debug包配置了 v2SigningEnabled false，导致后缀不一样；去掉后，debug包和release包后缀就都一样了。
但是v2SigningEnabled 为什么会影响打包后缀？

![image](https://user-images.githubusercontent.com/5340073/78235376-24295500-750b-11ea-8e23-603829054063.png)

**Comment by oncealong** [comment]
是debug包配置了 v2SigningEnabled false 导致。去掉后，debug包和release包后缀就一样了。
但是为什么v2SigningEnabled 会影响 AndResGuard打出来的apk名字？

**Comment by simpleton** [comment]
因为v1,v2签名的机制不同，导致执行对齐，签名的顺序不同
