### ISSUE TITLE
我混淆的资源中没有value的混淆文件 但是我的mapping中有将他混淆 导致后面压缩的时候文件数目不对 不能压缩 请问下这是什么情况

### ISSUE THREAD

**Issue by tailanx** [shwenzhang/AndResGuard#41]
![lbhxz h6qyj nyhe xo iu](https://cloud.githubusercontent.com/assets/6790747/13073607/b11bbcc6-d4da-11e5-9df1-b297240c674f.png) 但是我混淆资源中没有a4  ，请问下是什么情况
![27o4wg qpl1nn p1 5kphj](https://cloud.githubusercontent.com/assets/6790747/13073658/e3a323f0-d4da-11e5-93fb-5dc0cd6b0772.png)

**Comment by tailanx** [comment]
已经解决了

**Comment by simpleton** [comment]
@tailanx 回复晚了，不好意思。具体什么情况？
