### ISSUE TITLE
Cant follow the last step "andresguard/generate"

### ISSUE THREAD

**Issue by pranaysharma** [shwenzhang/AndResGuard#42]
Hi,
Thanks for the Library.
I am not able to follow the last step mentioned on the Repo using Gradle settings.
i.e. "Run andresguard/generate task to generate compressed APK."
Could you please elaborate how to perform this step?

**Comment by simpleton** [comment]
Sorry for late replay.
If you are using AndroidStudio, you can find the generate task which in andresguard group. just run it.
![image](https://cloud.githubusercontent.com/assets/454498/13135649/b5b7e614-d64d-11e5-90f0-8f546de6bbfc.png)

Or, you run `./gradlew generate` in your terminal.

**Comment by pranaysharma** [comment]
Great Thanks @simpleton . Just an addup for novices like me. "Tasks" can be found after clicking on the below Gradle button. It was on the Right most corner of my screen

![gradle](https://cloud.githubusercontent.com/assets/4221359/13136634/445d878c-d641-11e5-8da3-37cb71a3f688.jpg)
