### ISSUE TITLE
白名单支持规则配置吗

### ISSUE THREAD

**Issue by excitedhaha** [shwenzhang/AndResGuard#434]
比如 以 hh开头的文件

**Comment by DysaniazzZ** [comment]
可以用通配符的啊，用 hh* 就可以吧，你试试。比如我所有 gif 文件的开头都是 gif_，我就用 R.drawable.gif_* 这么弄的。但是现在新版本 gradle 和这个插件配合使用是有问题的，等 https://github.com/shwenzhang/AndResGuard/issues/436 这个解决了就可以了。
