### ISSUE TITLE
请支持gradle6.5

### ISSUE THREAD

**Issue by earlyup** [shwenzhang/AndResGuard#437]
升级gradle6.5之后，白名单失效

**Comment by 87926042** [comment]
我将gradle-plugin改成了4.1.0以下的就可以了，gradle也是6.5

**Comment by DysaniazzZ** [comment]
和这个 issue https://github.com/shwenzhang/AndResGuard/issues/436 一样

**Comment by svenjung** [comment]
不是gradle问题，是AGP问题，你提的应该是 #436

**Comment by simpleton** [comment]
fixed in #436
