### ISSUE TITLE
接入andResGuard后关键代码被混淆

### ISSUE THREAD

**Issue by CyanFlxy** [shwenzhang/AndResGuard#439]
使用resguardRelease打包，查看代码发现net.sqlcipher.database.SQLiteDatabase被混淆。
资源混淆前后的apk，这个类都是被混淆状态。
但是同一套代码使用assembleRelease打包，这个类没有被混淆。

SQLiteDatabase是ormlite-Android中的，内含native方法，会被默认防混淆规则保护。

**Comment by simpleton** [comment]
andResGuard并不涉及任何class的混淆
