### ISSUE TITLE
资源混淆会导致appsflyer无法发送网络请求

### ISSUE THREAD

**Issue by taugin** [shwenzhang/AndResGuard#447]
资源混淆后，会导致com > appsflyer > internal目录下的文件丢失，导致appsflyer无法发送网络请求

https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90

缺少资源文件
If you are using Android SDK V5 and above, make sure that in the APK file, in addition to the classes.dex and resources files, you also have folder com > appsflyer > internal with files a- and b- inside. 
Note: Before SDK 5.3.0, file names are a. and b.

在Android Studio中打开您的APK来检查您是否有必须的文件。请参阅以下屏幕截图以供参考。

如果这些文件丢失，则SDK无法向我们的服务器发出网络请求，您需要联系您的CSM或者Support寻求帮助。

**Comment by simpleton** [comment]
可以添加白名单解决

**Comment by hanxiaomeme** [comment]
> 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求
> 
> [https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90](https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91%E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90)
> 
> 缺少资源文件
> 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。
> 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b.
> 
> 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。
> 
> 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。

后来您是如何解决的?

**Comment by taugin** [comment]
升级了appsflyer的版本，就解决了，我升级的是5.4.4
















在 2021-09-08 10:43:28，"hanxiaomeme" ***@***.***> 写道：

资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求

https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90

缺少资源文件
如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。
注意：在 SDK 5.3.0 之前，文件名是 a. 和 b.

在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。

如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。

后来您是如何解决的?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanxiaomeme** [comment]
> 升级了appsflyer的版本，就解决了，我升级的是5.4.4 在 2021-09-08 10:43:28，"hanxiaomeme" ***@***.***> 写道： 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求 https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90 缺少资源文件 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b. 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。 后来您是如何解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我在白名单中添加了"*appsflyer_backup_rules*","*appsflyer*", 我现在的版本是
 implementation 'com.appsflyer:af-android-sdk:5.4.5'
    implementation 'com.android.installreferrer:installreferrer:2.1'
另外
FCM刚开始接受推送的时候也会崩溃 
我在白名单中补充了//通知渠道
            "*.R.string.fcm_fallback_notification_channel_label",
不知道是否可以,会不会造成其他的影响

**Comment by taugin** [comment]
白名单尽量多加点，这些都是公开的
















在 2021-09-08 11:06:22，"hanxiaomeme" ***@***.***> 写道：

升级了appsflyer的版本，就解决了，我升级的是5.4.4 在 2021-09-08 10:43:28，"hanxiaomeme" @.***> 写道： 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求 https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90 缺少资源文件 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b. 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。 后来您是如何解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我在白名单中添加了"appsflyer_backup_rules","appsflyer", 我现在的版本是
implementation 'com.appsflyer:af-android-sdk:5.4.5'
implementation 'com.android.installreferrer:installreferrer:2.1'
另外
FCM刚开始接受推送的时候也会崩溃
我在白名单中补充了//通知渠道
"*.R.string.fcm_fallback_notification_channel_label",
不知道是否可以,会不会造成其他的影响

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanxiaomeme** [comment]
> 白名单尽量多加点，这些都是公开的 在 2021-09-08 11:06:22，"hanxiaomeme" ***@***.***> 写道： 升级了appsflyer的版本，就解决了，我升级的是5.4.4 在 2021-09-08 10:43:28，"hanxiaomeme" @.***> 写道： 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求 https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90 缺少资源文件 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b. 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。 后来您是如何解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 我在白名单中添加了"appsflyer_backup_rules","appsflyer", 我现在的版本是 implementation 'com.appsflyer:af-android-sdk:5.4.5' implementation 'com.android.installreferrer:installreferrer:2.1' 另外 FCM刚开始接受推送的时候也会崩溃 我在白名单中补充了//通知渠道 "*.R.string.fcm_fallback_notification_channel_label", 不知道是否可以,会不会造成其他的影响 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

主要是现在我增加白名单主要靠测试的 我感觉效率太低了
我需要去看每个第三方库 然后一点点去加吗

**Comment by taugin** [comment]
他这个文档里面有白名单的配置的



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年09月08日 12:16 |
| 收件人 | ***@***.***> |
| 抄送至 | Liuzhao ***@***.******@***.***> |
| 主题 | Re: [shwenzhang/AndResGuard] 资源混淆会导致appsflyer无法发送网络请求 (#447) |

白名单尽量多加点，这些都是公开的 在 2021-09-08 11:06:22，"hanxiaomeme" @.> 写道： 升级了appsflyer的版本，就解决了，我升级的是5.4.4 在 2021-09-08 10:43:28，"hanxiaomeme" @.> 写道： 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求 https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90 缺少资源文件 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b. 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。 后来您是如何解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 我在白名单中添加了"appsflyer_backup_rules","appsflyer", 我现在的版本是 implementation 'com.appsflyer:af-android-sdk:5.4.5' implementation 'com.android.installreferrer:installreferrer:2.1' 另外 FCM刚开始接受推送的时候也会崩溃 我在白名单中补充了//通知渠道 "*.R.string.fcm_fallback_notification_channel_label", 不知道是否可以,会不会造成其他的影响 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

主要是现在我增加白名单主要靠测试的 我感觉效率太低了
我需要去看每个第三方库 然后一点点去加吗

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanxiaomeme** [comment]
> 他这个文档里面有白名单的配置的 发自 网易邮箱大师
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2021年09月08日 12:16 | | 收件人 | ***@***.***> | | 抄送至 | Liuzhao ***@***.******@***.***> | | 主题 | Re: [shwenzhang/AndResGuard] 资源混淆会导致appsflyer无法发送网络请求 (#447) | 白名单尽量多加点，这些都是公开的 在 2021-09-08 11:06:22，"hanxiaomeme" @.> 写道： 升级了appsflyer的版本，就解决了，我升级的是5.4.4 在 2021-09-08 10:43:28，"hanxiaomeme" @.> 写道： 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求 https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90 缺少资源文件 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b. 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。 后来您是如何解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 我在白名单中添加了"appsflyer_backup_rules","appsflyer", 我现在的版本是 implementation 'com.appsflyer:af-android-sdk:5.4.5' implementation 'com.android.installreferrer:installreferrer:2.1' 另外 FCM刚开始接受推送的时候也会崩溃 我在白名单中补充了//通知渠道 "*.R.string.fcm_fallback_notification_channel_label", 不知道是否可以,会不会造成其他的影响 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 主要是现在我增加白名单主要靠测试的 我感觉效率太低了 我需要去看每个第三方库 然后一点点去加吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我现在按照wiki中配置使用,其他问题也只能靠自己测试出现了

**Comment by taugin** [comment]
是的，别的问题只能自己尝试了



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年09月08日 12:29 |
| 收件人 | ***@***.***> |
| 抄送至 | Liuzhao ***@***.******@***.***> |
| 主题 | Re: [shwenzhang/AndResGuard] 资源混淆会导致appsflyer无法发送网络请求 (#447) |

他这个文档里面有白名单的配置的 发自 网易邮箱大师
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2021年09月08日 12:16 | | 收件人 | @.> | | 抄送至 | Liuzhao @.@.> | | 主题 | Re: [shwenzhang/AndResGuard] 资源混淆会导致appsflyer无法发送网络请求 (#447) | 白名单尽量多加点，这些都是公开的 在 2021-09-08 11:06:22，"hanxiaomeme" @.> 写道： 升级了appsflyer的版本，就解决了，我升级的是5.4.4 在 2021-09-08 10:43:28，"hanxiaomeme" @.> 写道： 资源重制后，会导致com > appsflyer > 内部目录下的文件丢失，导致appsflyer无法发送网络请求 https://support.appsflyer.com/hc/zh-cn/articles/207032126-%E9%80%82%E7%94%A8%E4%BA%8E%E5%BC%80%E5%8F%91 %E4%BA%BA%E5%91%98%E7%9A%84Android-SDK%E9%9B%86%E6%88%90#%E9%9B%86%E6%88%90 缺少资源文件 如果您使用的是Android SDK V5及以上版本，请确保在APK文件中，除了classes.dex和resources文件之外，还有文件夹com > appsflyer > internal，里面有a-和b-文件。 注意：在 SDK 5.3.0 之前，文件名是 a. 和 b. 在 Android Studio 中打开您的 APK 来检查您是否有必须的文件。请查看以下屏幕截图以供参考。 如果这些文件丢失，则 SDK 无法向我们的服务器发出网络请求，您需要联系您的 CSM 或支持寻求帮助。 后来您是如何解决的? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 我在白名单中添加了"appsflyer_backup_rules","appsflyer", 我现在的版本是 implementation 'com.appsflyer:af-android-sdk:5.4.5' implementation 'com.android.installreferrer:installreferrer:2.1' 另外 FCM刚开始接受推送的时候也会崩溃 我在白名单中补充了//通知渠道 "*.R.string.fcm_fallback_notification_channel_label", 不知道是否可以,会不会造成其他的影响 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 主要是现在我增加白名单主要靠测试的 我感觉效率太低了 我需要去看每个第三方库 然后一点点去加吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我现在按照wiki中配置使用,其他问题也只能靠自己测试出现了

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
