### ISSUE TITLE
这是肿么回事？

### ISSUE THREAD

**Issue by amyliu1062** [shwenzhang/AndResGuard#45]
在运行gradle中andresguard/generate时
报了下面这两个错误：

an not find the compress dataresFile=res/anim/slide_top_out.xml
can not find res file, you delete it? path: resFile=/Users/liudan/work/xx/build/outputs/apk/AndResProguard/temp/res/anim/slide_top_out.xml
can not find the compress dataresFile=res/anim/xr_slide_in_top.xml
can not find res file, you delete it? path: resFile=/Users/liudan/work/xx/build/outputs/apk/AndResProguard/temp/res/anim/xr_slide_in_top.xml
can not find the compress dataresFile=res/anim/xr_slide_out_bottom.xml
can not find res file, you delete it? path: resFile=/Users/liudan/work/xx/build/outputs/apk/AndResProguard/temp/res/anim/xr_slide_out_bottom.xml
以上资源在项目中有

java.io.IOException: Cannot run program "/Users/liudan/work/file/zip": error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:450)
	at java.lang.Runtime.exec(Runtime.java:347)
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:154)
	at com.tencent.mm.androlib.ResourceApkBuilder.alignApk(ResourceApkBuilder.java:138)
	at com.tencent.mm.androlib.ResourceApkBuilder.buildApk(ResourceApkBuilder.java:48)
这个是zipAlignPath和sevenZipPath，文件权限我都设置成everyone可读可写了。

不知道是什么问题，可以指点一下吗？

**Comment by simpleton** [comment]
第二个问题是权限问题，只要有权限有OK。

第一个问题你有没有试过clean一下再build.

**Comment by amyliu1062** [comment]
java.io.IOException: error=13, Permission denied。这个要求程序或者哪里设置什么权限吗？我是Mac电脑，文件夹右键直接修改的权限

**Comment by simpleton** [comment]
只要在terminal可以运行zip工具即可。

2016-02-19 17:08 GMT+08:00 amyliu1062 <notifications@github.com>:

**Comment by amyliu1062** [comment]
第一个问题确实认真build就解决了。第二个问题是我路径写错了😢。也可以生成安装包了，但是安装包不能用，查找原因发现，执行过程中报了一个如下错误，
Execution failed for task ':xr_patient:compileRetrolambdaXingRenRelease'。但是我不明白这个task是怎么生成的，可以指点一下吗？或者加我QQ1062669032

**Comment by simpleton** [comment]
Retrolambda另外是一个让低版本java可以用lambda的工具库

2016-02-21 14:51 GMT+08:00 amyliu1062 <notifications@github.com>:

**Comment by amyliu1062** [comment]
这个我知道呀，然后呢

**Comment by amyliu1062** [comment]
尝试用gradle的方式，回报错误objc[11293]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.暂时应该没办法解决；
使用命令行的方式，java -jar andresguard.jar xr_debug.apk，报错误“文档中根元素后面的标记必须格式正确。”。config.xml内容如下：
<issue id="property">
	<seventzip value="false"/>
	<metaname value="META_INF"/>
</issue>
<issue id="whitelist" isactive="false">
	<path value="com.xingren.xrpatient.R.drawable.smiley_*"/>
</issue>
<issue id="compress" isactive="false">
	<path value="res/drawable-hdpi/smiley_?.png"/>
</issue>

**Comment by amyliu1062** [comment]
<issue id="property">
	<seventzip value="false"/>
	<metaname value="META_INF"/>
</issue>
<issue id="whitelist" isactive="false">
	<path value="com.xingren.xrpatient.R.drawable.smiley_*"/>
</issue>
<issue id="compress" isactive="false">
	<path value="res/drawable-hdpi/smiley_?.png"/>
</issue>

**Comment by amyliu1062** [comment]
“<issue id="property">
	<seventzip value="false"/>
	<metaname value="META_INF"/>
</issue>
<issue id="whitelist" isactive="false">
	<path value="com.xingren.xrpatient.R.drawable.smiley_*"/>
</issue>
<issue id="compress" isactive="false">
	<path value="res/drawable-hdpi/smiley_?.png"/>
</issue>”

**Comment by amyliu1062** [comment]
到哪里下载resourcesproguard.jar怎么得到？

**Comment by simpleton** [comment]
@amyliu1062 可能readme有点过时，如果用命令好工具。可以在tools_output里找到命令行的jar包。

**Comment by amyliu1062** [comment]
readme中也没有给出能生成jar的命令行，命令是什么呢？

**Comment by simpleton** [comment]
下载代码，编译cli工程即可。
