### ISSUE TITLE
请问是不是不支持M1芯片？

### ISSUE THREAD

**Issue by is1988** [shwenzhang/AndResGuard#459]
我在老的MacBook上运行正常，在M1上报错
`Could not find SevenZip-1.2.21-osx-aarch_64.exe`
而我发现老的MacBook下载的是x86的SevenZip，也就是
`Could not find SevenZip-1.2.21-osx-x86_64.exe`

aarch的找不到，请问我改怎么做？

**Comment by simpleton** [comment]
可以通过use7zip = false,或者自行制定7zip的binary路径来workaround

**Comment by simpleton** [comment]
duplicated #444
