### ISSUE TITLE
运行出错，找不到入口类。我用的是jdk1.6+win8。

### ISSUE THREAD

**Issue by lizhuangs** [shwenzhang/AndResGuard#46]
D:\as\thinkAndroid\AndResGuard>java -jar AndResGuard-gradle-plugin-1.1.2.jar thinkandroid_V1.0_2016-02-24_normal.apk
Failed to load Main-Class manifest attribute from
AndResGuard-gradle-plugin-1.1.2.jar
解压打开发现里面的确没有配置入口类。是jdk过低？

**Comment by shwenzhang** [comment]
用错了jar,看tool_output

**Comment by lizhuangs** [comment]
之前是直接点击的首页的download。我重新下载了tool_output中的jar。还是提示出错。我测试的是简单用法。
D:\as\thinkAndroid\AndResGuard>java -jar AndResGuard-cli-1.1.0.jar thinkandroid_V1.0_2016-02-24_normal.apk
Invalid or corrupt jarfile AndResGuard-cli-1.1.0.jar

**Comment by simpleton** [comment]
@lizhuangs 你试试运行tool_output里的相应脚本，也是报同样的错误么？

**Comment by lizhuangs** [comment]
运行里面的脚本没有错误。求解决，另外gradle-plugin是1.1.2，这个还是1.1.0

**Comment by simpleton** [comment]
核心功能没有区别，因为1.1.2都是修复一些gradle plugin的一些bug。如何你使用命令行工具，可以先使用tool_output里的jar包。

我后续会更新一些readme，并写个脚本自动同步最新版本的jar包。这里我先close了，有其他问题可以开心的issue。 

多谢你的issue。

**Comment by lizhuangs** [comment]
我找到问题了，昨天下载的jar有问题，无法解压和反编绎，重新下载了一个好使了。
