### ISSUE TITLE
资源不对应bug

### ISSUE THREAD

**Issue by simpleton** [shwenzhang/AndResGuard#47]
我在使用andresguard的时候发现一个问题，我在重打包的时候抛出一个IO异常，日志打印出原因是DestResDir 922 rawResDir 923（源文件和改变后的文件个数不等），经过排查发现解压的apk的raw文件夹中生成了一个config.properties的文件，这个文件没有被复制到混淆之后的资源文件夹中去。如下图（前面一张是解压的目录）：
![image](https://cloud.githubusercontent.com/assets/454498/13279283/91e38fd6-db11-11e5-9e44-af2c0505ced8.png)
![image](https://cloud.githubusercontent.com/assets/454498/13279285/9544c442-db11-11e5-93c0-dd7d393c9182.png)

**Comment by shwenzhang** [comment]
fixed
