### ISSUE TITLE
拆包后 使用资源混淆，打开第二个dex中的activity就崩溃

### ISSUE THREAD

**Issue by EvilsoulM** [shwenzhang/AndResGuard#48]
Unable to instantiate activity ComponentInfo{com.xxx.xxx/com.xxx.xxx.xxx.xxx.WalletActivity}: java.lang.ClassNotFoundException: Didn't find class "com.xxxx.xxx.xxx.xxx.WalletActivity" on path: DexPathList[[zip file "/data/app/com.xxx.xxx-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-1/lib/arm, /data/app/com.xxx.xxx-1/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]

**Comment by simpleton** [comment]
你是把第二个dex放在哪里？ 使用的是google的multidex lib么？可以查看一下这个类是否还在第二个dex中。按道理andresguard不会更改任何dex文件的，只更改了resource.asrc。

**Comment by EvilsoulM** [comment]
没使用压缩前，我们是两个dex但是用了压缩后 变成了一个dex 就蹦了

**Comment by simpleton** [comment]
@EvilsoulM 你们第二个dex是放在哪里的？

**Comment by EvilsoulM** [comment]
[dex.jpg](http://chuantu.biz/t2/28/1456317540x1965191032.jpg)

**Comment by EvilsoulM** [comment]
@shwenzhang 问题找到了～是我们在资源压缩后又对包做了一次拆包～那次task执行错误了～感谢你啦～
