### ISSUE TITLE
ResourceApkBuilder.java中dos执行报错

### ISSUE THREAD

**Issue by lizhuangs** [shwenzhang/AndResGuard#50]
gradle中执行dos命令那步出现问题：
java.io.IOException: Cannot run program "D:\Program": CreateProcess error=2, ?????????
在windows系统中一般都安装在program file目录，目录中包含了空格。导致jdk和7zip执行通过不了。

需要要路径前后加上\"引起来。

**Comment by simpleton** [comment]
好的，我修复一下。

**Comment by simpleton** [comment]
@lizhuangs 发布了1.1.3，修复了这个问题。

**Comment by lizhuangs** [comment]
测试好使了，Tks！顺便问一下：运行andresguard/generate的gradle任务，这句话是什么意思，我在1.1.1的时候使用generate可以，但是1.1.3中不行，后来改成运行resguard这个就好使了。我在源码中看到的是project.tasks.create('resguard', AndResGuardSchemaTask)，好像英文的文档写的是Run andresguard/resguard task to generate compressed APK，是不是写成运行gradle resguard容易理解？

**Comment by simpleton** [comment]
@lizhuangs 因为原先的generate有点太宽泛，现在改成resguard了。刚才中文的readme没有update。我已经更新了
