### ISSUE TITLE
Integrate 7zip to library

### ISSUE THREAD

**Issue by simpleton** [shwenzhang/AndResGuard#52]
It will be useful when we run resguard task in third-part CI server.

**Comment by simpleton** [comment]
http://mvnrepository.com/artifact/com.carrotgarden.jwrapper/jwrapper-7zip-jbinding/1.0.0

**Comment by nianzixin** [comment]
我用的是mac，按照gradle配置会报错呢？怎么回事？

**Comment by simpleton** [comment]
@nianzixin 麻烦贴一下错误的log

**Comment by a1113567888** [comment]
Error:Could not find com.tencent.mm:AndResGuard-gradle-plugin:1.1.5.
Searched in the following locations:
    https://repo1.maven.org/maven2/com/tencent/mm/AndResGuard-gradle-plugin/1.1.5/AndResGuard-gradle-plugin-1.1.5.pom
    https://repo1.maven.org/maven2/com/tencent/mm/AndResGuard-gradle-plugin/1.1.5/AndResGuard-gradle-plugin-1.1.5.jar
    https://maven.fabric.io/public/com/tencent/mm/AndResGuard-gradle-plugin/1.1.5/AndResGuard-gradle-plugin-1.1.5.pom
    https://maven.fabric.io/public/com/tencent/mm/AndResGuard-gradle-plugin/1.1.5/AndResGuard-gradle-plugin-1.1.5.jar
Required by:
    KuaiHuoYun:com.kuaihuoyun.android.user:unspecified
报错:
在gradle里面设置了  
apply plugin: 'AndResGuard'
    dependencies {
        classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.1.5'
    }

**Comment by simpleton** [comment]
@a1113567888 请不要在不相关的issue里跟帖。
你这个问题是没有增加jcenter作为源在repositories里
