### ISSUE TITLE
How can I disable signConfig check if run ./gradlew resguard task

### ISSUE THREAD

**Issue by shawnlinboy** [shwenzhang/AndResGuard#53]
Now the console will tell `Could not find property 'release' on SigningConfig container.`. What if I don't need this closure check and I want sign my apk later by myself?

**Comment by shwenzhang** [comment]
in command line tool, you can set sign isactive=false

**Comment by simpleton** [comment]
@shawnlinboy sorry for late feedback. 
Currently, the gradle plugin didn't support generate apk without sign info, I'll fix it at next release.
You can use the command line tooling as workaround now.

**Comment by shawnlinboy** [comment]
@simpleton Sounds great, and I really appreciate for you guys open-sourcing this awesome project.

**Comment by simpleton** [comment]
close now, plz try 1.1.5.
free feel reopen this issue, if the bug didn't fixed.
