### ISSUE TITLE
可以把签名前后的方法暴露出来么，见描述

### ISSUE THREAD

**Issue by godzillanono** [shwenzhang/AndResGuard#56]
public void buildApk(HashMap<String, Integer> compressData) throws IOException,InterruptedException
{
        insureFileName();
        generalUnsignApk(compressData);
        signApk();         // 这一步由我们自己来签名，前后的方法暴露出来
        use7zApk(compressData);
        alignApk();
}

**Comment by simpleton** [comment]
@godzillanono 没有很理解你的意图，‘AndResGuard’ 会读
```gradle
signingConfigs {
        release {
            storeFile file(".xxx")
            storePassword "xxx"
            keyAlias "xxx"
            keyPassword "xxx"
        }
}
```
里的签名信息并签名。

**Comment by godzillanono** [comment]
@simpleton 就是我也拿不到签名信息，我只能提供签名后的apk

**Comment by godzillanono** [comment]
@simpleton 估计这样的需求比较特殊。。。我自己改改源代码吧，还是非常感谢分享！

**Comment by simpleton** [comment]
欢迎Pull Request
