### ISSUE TITLE
res path mapping 里面找不到res/values的映射，请问这是什么问题？

### ISSUE THREAD

**Issue by c1024** [shwenzhang/AndResGuard#57]
我混淆完生成的esource_mapping.txt里面有如下内容，但找不到res/values的映射。请问这是什么问题？
res/anim -> r/a
    res/color -> r/b
    res/color-v11 -> r/c
    res/color-v23 -> r/d
    res/drawable -> r/e
    res/drawable-hdpi-v4 -> r/f
    res/drawable-ldrtl-hdpi-v17 -> r/g
    res/drawable-ldrtl-mdpi-v17 -> r/h
    res/drawable-ldrtl-xhdpi-v17 -> r/i
    res/drawable-ldrtl-xxhdpi-v17 -> r/j
    res/drawable-ldrtl-xxxhdpi-v17 -> r/k
    res/drawable-mdpi-v4 -> r/l
    res/drawable-nodpi-v4 -> r/m
    res/drawable-sw321dp-xhdpi-v13 -> r/n
    res/drawable-sw600dp-v13 -> r/o
    res/drawable-v21 -> r/p
    res/drawable-v23 -> r/q
    res/drawable-xhdpi-v4 -> r/r
    res/drawable-xxhdpi-v4 -> r/s
    res/drawable-xxxhdpi-v4 -> r/t
    res/layout -> r/u
    res/layout-sw600dp-v13 -> r/v
    res/layout-v14 -> r/w
    res/layout-v17 -> r/x
    res/layout-v21 -> r/y
    res/mipmap-xhdpi-v4 -> r/z

**Comment by simpleton** [comment]
@c1024 因为values信息会编译进resource.arsc，这里不用做路径混淆。
