### ISSUE TITLE
java.io.IOException: Cannot run program "zipalign": error=2, No such file or directory

### ISSUE THREAD

**Issue by Witype** [shwenzhang/AndResGuard#59]
手动传入zipalign的路径也会报同样的错误
![image](https://cloud.githubusercontent.com/assets/6899329/14633455/3c402e62-0650-11e6-8ca7-e6541e993689.png)

![image](https://cloud.githubusercontent.com/assets/6899329/14633324/ae6acc50-064f-11e6-8c97-3d6ead9b030f.png)
路径是完全正确的，走到这就回出现这个错误。

**Comment by simpleton** [comment]
@Witype 我这边测试了同样的命令，没有复现问题。
请提供一下完整的log和使用的版本。
