### ISSUE TITLE
为什么在compressFilePattern中指定了压缩png，但是有些png图片还是没有被压缩呢。

### ISSUE THREAD

**Issue by hunji66** [shwenzhang/AndResGuard#61]
压缩算法依然为store

**Comment by simpleton** [comment]
@hunji66 可否把具体的压缩前apk和压缩后apk以及你压缩使用的命令发到我的邮箱呢？并简单描述一下哪些文件没有被压缩。

**Comment by hunji66** [comment]
@simpleton 
`apply plugin: 'AndResGuard'`
`    compressFilePattern = [
            "*.png",
            "*.jpg",
            "*.jpeg",
//            "*.gif",
            "*.webp",
            "resources.arsc"
    ]`
`    mappingFile = null
    use7zip = true
    useSign = true
    keepRoot = false`

**Comment by hunji66** [comment]
是不是对于7 zip -mx9 模式下， 依然会有文件为 stored呢?

**Comment by shwenzhang** [comment]
@hunji66 , 系统不压缩png，jpg这些有一方面原因就是他们一般来说压缩率都非常小。有部分的png文件压缩前后大小一样，是很正常的。

**Comment by hunji66** [comment]
谢谢解答啦
