### ISSUE TITLE
使用Gradle时，mappingFile配置错误

### ISSUE THREAD

**Issue by liutan** [shwenzhang/AndResGuard#62]
在使用grdale时，配置mappingFile 设置类型为String/File 时报错

> What went wrong:
Execution failed for task ':app:resguard'.
No signature of method: com.tencent.mm.resourceproguard.InputParam$Builder.setMappingFile() is applicable for argument types: (java.lang.String) values: [/Users/liutan/Documents/a.txt]
  Possible solutions: setMappingFile(java.io.File)'

查看源码发现 AndResGuardExtension 中mappingFile类型为String，但在 AndResGuardSchemaTask 中直接使用的 InputParam.Builder 的 setMappingFile 方法，不知道是不是这里的BUG

**Comment by simpleton** [comment]
是bug， 已fix。多谢issue。
