### ISSUE TITLE
如何通过gradle命令执行AndResGuard？

### ISSUE THREAD

**Issue by LichFaker** [shwenzhang/AndResGuard#64]
我通过`gradle`的方式集成最新的`AndResGuard`，使用`gradle clean apkRelease`编译项目，发现生成的apk并没有混淆资源

**Comment by simpleton** [comment]
使用'/gradlew resguard' 可以得到混淆包

**Comment by LichFaker** [comment]
成功了， 是我误用了`gradle andresguard`, 谢谢
