### ISSUE TITLE
执行gradlew resguard报错，配置都是按照文档的。

### ISSUE THREAD

**Issue by zhonghanwen** [shwenzhang/AndResGuard#65]
![image](https://cloud.githubusercontent.com/assets/12220537/14906705/10574094-0df1-11e6-9b27-25589d6c6862.png)

**Comment by simpleton** [comment]
可以确认下release签名信息是否配置正确.
```gradle
signingConfigs {
        release {
            storeFile file(***)
            storePassword "***"
            keyAlias "***"
            keyPassword "***"
        }
}
```

**Comment by zhonghanwen** [comment]
@simpleton 使用Gradle集成会出现上面的情况，使用工具第二种方法进行混淆就无问题。

**Comment by simpleton** [comment]
方便贴一下build.gradle文件么？我帮你看下。看提示就是签名信息没有配置正确

**Comment by simpleton** [comment]
优化了签名获取的方法，请更新到1.1.8
