### ISSUE TITLE
关于白名单

### ISSUE THREAD

**Issue by IanChengYuen** [shwenzhang/AndResGuard#68]
有什么方法可以快速统计项目中需要加入白名单的资源吗

**Comment by simpleton** [comment]
我现在也没有什么特别好的办法，要不就可以直接运行时计算了。

对于广泛使用的开源或闭源组件，希望大家可以把遇到的坑也贴在issue里。
如果是自己的项目，所有直接通过`getIdentifier `或者直接访问的资源都需要加入白名单。
