### ISSUE TITLE
友盟 微博分享  需要添加白名单

### ISSUE THREAD

**Issue by DimlyDiscernible** [shwenzhang/AndResGuard#69]
新浪微博分享时出现 获取资源ID失败:  type=drawable  name=sina_web_default

所以如果有新浪微博分享时需要在白名单里添加 该图片：
"<your_package_name>.R.drawable.sina*"

**Comment by simpleton** [comment]
多谢反馈。

**Comment by simpleton** [comment]
1.1.8 在readme里有增加了相关白名单
