### ISSUE TITLE
为什么没有默认开启图片压缩

### ISSUE THREAD

**Issue by loghanfeng** [shwenzhang/AndResGuard#70]
你好，
请问你为什么没有默认开启图片压缩，在config.xml里面设置的，
<issue id ="compress" isactive="false">
是打开会有什么问题吗？
比如每次加载图片时会导致更多的解压图片而带来的消耗。
或常驻native内存?

**Comment by simpleton** [comment]
压缩图片只是额外的功能，所以没有默认开启。
PS:如果你的resource.arsc 小于1M压缩是绝对安全的；如果大于1M，minSdk是4.0以上的也OK。
具体原因参见[这里](http://ponystyle.com/blog/2010/03/26/dealing-with-asset-compression-in-android-apps/)

**Comment by simpleton** [comment]
ref #84
