### ISSUE TITLE
打包生成的apk上传到yandex失败

### ISSUE THREAD

**Issue by figofuture** [shwenzhang/AndResGuard#76]
[yandex](https://developer.store.yandex.com/)的app store会解析上传的apk，从apk中抽取出app icon，做过资源混淆的apk会导致抽取app icon失败，从而导致无法将apk上传到yandex的发布平台，请测试下如何解决，谢谢

**Comment by simpleton** [comment]
可以增加icon资源到白名单，白名单的资源是不做混淆的

**Comment by figofuture** [comment]
加了，好像没用。你可以测试下的。主要是路径，不光是资源名称。

On Thu, Jun 30, 2016 at 3:52 PM, Sim Sun <notifications@github.com> wrote:

> 可以增加icon资源到白名单，白名单的资源是不做混淆的
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/shwenzhang/AndResGuard/issues/76#issuecomment-229587494>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP4PULYO-gde5d5OQVQQuLMgSxQ30u6ks5qQ3XWgaJpZM4JB3xs>
> .
>



-- 
Best Regards,
                     future

**Comment by simpleton** [comment]
@figofuture 好的，我稍后试一下

**Comment by simpleton** [comment]
@figofuture 抱歉，周中有点忙，所以回复晚了。我使用`AndResGuard-example`编译出来的apk，可以上传到yandex平台，如果你想keep住icon的全路径，AndResGuard也是支持的，具体可以参考我关联这个issue的commit。

**Comment by figofuture** [comment]
但是我不想所有的资源都keeproot，只想icon这个资源keeproot。如果所有资源都keeproot的话，控制粒度太粗了，在节省apk空间和保护资源的力度上会大大下降。

On Mon, Jul 4, 2016 at 2:52 AM, Sim Sun <notifications@github.com> wrote:

> @figofuture <https://github.com/figofuture> 抱歉，周中有点忙，所以回复晚了。我使用
> AndResGuard-example
> 编译出来的apk，可以上传到yandex平台，如果你想keep住icon的全路径，AndResGuard也是支持的，具体可以参考我关联这个issue的commit。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shwenzhang/AndResGuard/issues/76#issuecomment-230168971>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP4Parv4XS-XAPiipwHEURnZsc1WmJ8ks5qSATzgaJpZM4JB3xs>
> .
>



-- 
Best Regards,
                     future

**Comment by simpleton** [comment]
@figofuture 由于我没有建立SNAPSHOT版的repo，可否下一下repo，自己构建1.1.10-SNAPSHOT版本来尝试一下，用keepmapping的形式是否满足你的需求？

PS：我用example是直接可以上传的，不加任何keep约束。

**Comment by figofuture** [comment]
我的意思是我不想用keeproot，这样别的资源也会keeproot?不知道你是否明白我说的意思。我看到你的提交了一个修改是keeproot从之前的false改成了true，我不想这样改，如果这样的话，别的不受影响的资源(ong,jpg,xml等)都会keeproot，我并不想这样。

2016-07-04 18:20 GMT+08:00 Sim Sun <notifications@github.com>:

> @figofuture <https://github.com/figofuture>
> 由于我没有建立SNAPSHOT版的repo，可否下一下repo，自己构建1.1.10-SNAPSHOT版本来尝试一下，用keepmapping的形式是否满足你的需求？
>
> PS：我用example是直接可以上传的，不加任何keep约束。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shwenzhang/AndResGuard/issues/76#issuecomment-230257418>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP4PSq8F9O3hz1YvBcA69-Q_Gqlcle-ks5qSN5VgaJpZM4JB3xs>
> .
>



-- 
Best Regards,
                     future

**Comment by simpleton** [comment]
@figofuture 我指的是用Keepmapping，不是用keeproot。可以参考41ffacda这个commit的提交

**Comment by figofuture** [comment]
试了不行哦，还是报错，解析icon发生异常。

有截屏为证！

​

On Mon, Jul 4, 2016 at 9:55 PM, Sim Sun <notifications@github.com> wrote:

> @figofuture <https://github.com/figofuture>
> 我指的是用Keepmapping，不是用keeproot。可以参考41ffacda这个commit的提交
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shwenzhang/AndResGuard/issues/76#issuecomment-230296214>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP4PZ24HsZ9b11PacIxAsN9JmxjI0zSks5qSRDFgaJpZM4JB3xs>
> .
>



-- 
Best Regards,
                     future

**Comment by figofuture** [comment]
![image](https://cloud.githubusercontent.com/assets/260157/16567177/28650568-424e-11e6-8af5-d1d6fbc4b476.png)

**Comment by simpleton** [comment]
那可能不是icon path的原因了，可以联系这个网站的support看下是什么原因。

**Comment by figofuture** [comment]
如果keeproot没问题啊，但是不想这样改。

On Tue, Jul 5, 2016 at 7:02 PM, Sim Sun <notifications@github.com> wrote:

> 那可能不是icon path的原因了，可以联系这个网站的support看下是什么原因。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shwenzhang/AndResGuard/issues/76#issuecomment-230449139>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP4PYt6C7VfuHnLsatQdXrs_LRzZZXvks5qSjmogaJpZM4JB3xs>
> .
>



-- 
Best Regards,
                     future

**Comment by simpleton** [comment]
@figofuture keep mapping 可以更小粒度的控制，可以尝试下是什么资源导致的问题。

**Comment by figofuture** [comment]
就是app的icon啊！

On Tue, Jul 5, 2016 at 8:47 PM, Sim Sun <notifications@github.com> wrote:

> @figofuture <https://github.com/figofuture> keep mapping
> 可以更小粒度的控制，可以尝试下是什么资源导致的问题。
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/shwenzhang/AndResGuard/issues/76#issuecomment-230468306>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAP4PbYPu7pw-pRGeODZ7cD1KVftOxazks5qSlJogaJpZM4JB3xs>
> .
>



-- 
Best Regards,
                     future
