### ISSUE TITLE
gradlew resguard 可以指定buildType么？？

### ISSUE THREAD

**Issue by vihuela** [shwenzhang/AndResGuard#79]

**Comment by simpleton** [comment]
一般只有release版会要求资源混淆。

**Comment by vihuela** [comment]
好吧。。

**Comment by hacket** [comment]
现在我们会定义多个`buildType`，其中会有`releaseLog`，支持log输出，proguard和resguard基本和release包没区别，只是打开了log方便跟踪crash，然后给qa测试。resguard目前只支持release吧，能否支持下指定`buildType`。

**Comment by simpleton** [comment]
ref #106
