### ISSUE TITLE
jarsigner 调用方式太过简陋

### ISSUE THREAD

**Issue by xen0n** [shwenzhang/AndResGuard#81]
[问题代码](https://github.com/shwenzhang/AndResGuard/blob/master/AndResGuard-core/src/main/java/com/tencent/mm/androlib/ResourceApkBuilder.java#L107-L112)

遇到密码或密钥别名中含有空格等字符的情况，Gradle 就会崩溃，这里应该对传入参数进行转义处理。

（一周后可写补丁，现在比较忙，不好写

**Comment by simpleton** [comment]
这里写的是有点偷懒，多谢反馈

2016-07-21 1:52 GMT+08:00 Wang Xuerui <notifications@github.com>:

**Comment by xen0n** [comment]
@simpleton 突然发现根本不用转义，直接构造argv就行了，因此PR已开 😄

**Comment by xen0n** [comment]
卧槽，GitHub web提交PR界面好蠢，默认提交到自己的fork。。。这次确实提交了

**Comment by simpleton** [comment]
ref #93
