### ISSUE TITLE
signed_7zip/_aligned包下Apk问题

### ISSUE THREAD

**Issue by vihuela** [shwenzhang/AndResGuard#83]
一共生成5个包，signed_7zip/_aligned包下信鸽推送无用，检查之后发现信鸽没有资源引用，所以不知道为什么？？

**Comment by simpleton** [comment]
@lyao，信鸽是已什么方式继承的呢？你方便对example做一个继承信鸽的PR么？

**Comment by vihuela** [comment]
抱歉，才看到，今天早上分支example时，无意拷贝so全机型包，可以了，看来是android的坑，多谢
