### ISSUE TITLE
resources.arsc压缩会影响性能吗？

### ISSUE THREAD

**Issue by c1024** [shwenzhang/AndResGuard#84]
在知乎看到一篇文章(https://zhuanlan.zhihu.com/p/21543787) ,有一段话：
resources.arsc 在 APK 安装之后仍需要被频繁的读取，如果将它进行压缩，在每次读取前系统都必须进行解压的操作，从性能上考量这显然是得不偿失的。所以，赶紧摒弃通过压缩 resources.arsc 来给 APK 瘦身的方法吧。
请问resources.arsc压缩会影响性能吗？

**Comment by simpleton** [comment]
先说我的观点：我觉得会有影响，但影响非常小。

具体的benchmark我没有做过，但我觉得resources.arsc的压缩最大的劣势是内存而不是运行时的速度。不压缩的resources.arsc系统可以使用mmap来节约内存的使用。一个app的资源至少被3个进程所持有（自己, launcher, system），所以mmap可以很大的节约内存使用。而压缩的resources.arsc会存在于每个进程中，可以使用`dumpsys  meminfo  your.package.name`来查看压缩与不压缩内存的差异。

AndResGuard也会提供不压缩resource.arsc选项，来方便大家选择不同的配置。

PS：也欢迎大家做相关的benchmark

**Comment by gezihua** [comment]
微信也是因为内存问题所以不压缩的吗？

**Comment by simpleton** [comment]
@gezihua 微信以前是压缩的，现在的状态我不太清楚。
总的来说google是不推荐压缩这个文件的，因为会更消耗系统资源。这个还是要自己来权衡。ref  #233

**Comment by drakeet** [comment]
我的应用最近尝试了一番「放弃 resources.arsc 压缩」，安装包从 5MB 变到 7MB，但最后线上统计数据以及我后来使用一个三星 S9+ (Android 10) & 小米 2s (Android 5.1.1) 进行反复测试，最终都发现「放弃 resources.arsc 压缩」对冷启动的影响微乎其微，几乎观察到不到性能提升。所以准备恢复对 resources.arsc 的压缩...
