### ISSUE TITLE
androidstudio 升级到2.1.3 gradle 升级到gradle-2.14.1-all.zip 出现下面错误

### ISSUE THREAD

**Issue by xujinyang** [shwenzhang/AndResGuard#88]
* What went wrong:
Circular dependency between the following tasks:
:app:packageRelease
\--- :app:uploadReleaseSymtabFile
     \--- :app:packageRelease (*)

(*) - details omitted (listed previously)

**Comment by simpleton** [comment]
收到，多谢反馈。我周末看一下

**Comment by simpleton** [comment]
我将自己的版本也升级到2.14.1没有复现你的问题，麻烦问下`app:uploadReleaseSymtabFile`是什么任务的task?

**Comment by xujinyang** [comment]
不知道发生了什么，今天过来，又正常了，而且我同事的电脑也正常了。。。。好奇怪
