### ISSUE TITLE
About Resources$NotFoundException

### ISSUE THREAD

**Issue by 1024iCloud** [shwenzhang/AndResGuard#92]
@simpleton  使用工具时，打包是出现找不到资源，具体在：

R.mipmap 下,使用方法 ```getResources().openRawResource(int id)``` 会爆这个错误

```
android sdk:24
             build tool 24.0.1

mobile sdk 5.0.1
       name xiaomi


toolversion 1.1.9

```

**Comment by simpleton** [comment]
有具体的Log么？或者方便把apk包发我，我debug下。sunsj1231[at]gmail.com

**Comment by MichaelNing** [comment]
@shwenzhang  你好，我在使用jenkins打包的时候，一直报错，各种方式试了都无解。但是本地是通过的。
![error](https://cloud.githubusercontent.com/assets/5234517/18805674/117e4330-8247-11e6-957d-0dad287cc342.png)

**Comment by simpleton** [comment]
从log看是签名不正确，建议有问题可以重提一个issue，而不是在别的issue下append自己的问题。

**Comment by simpleton** [comment]
🤔🤔🤔

当时这个报错就替换了。

用友盟的UMImage image = new UMImage(this,R.mipmap.ic_launcher)
工具打包时，没有爆错误，打开分享设置图片就报错了。直接可以用这句测试下。

um http://dev.umeng.com/social/android/sdk-download        v5.2.1




在 2016年9月26日，15:33，Shengjie Sun <sunsj1231@gmail.com> 写道：

能否提供一下你所集成的sdk的连接，或者提一个PR，在example集成好这个sdk.

On Mon, Sep 26, 2016 at 3:22 PM, Moo <chinaume@163.com> wrote:
@simpleton 

github 原文:
		使用工具时，打包是出现找不到资源，具体在：
R.mipmap 下,使用方法 getResources().openRawResource(int id) 会爆这个错误

android sdk:24
             build tool 24.0.1

mobile sdk 5.0.1
       name xiaomi


toolversion 1.1.9

之前用的是1.1.3的版本，可用mipmap,

实例：
友盟分享sdk里面的UMImage line:74

if(var2 instanceof Integer) {
    this.i = new UMImage.ResConvertor(var1, ((Integer)var2).intValue());
}
line:261
AssetFileDescriptor var4 = this.a.getResources().openRawResourceFd(this.b);
var3 = var4.createInputStream();
在项目debug情况下用R.mipmap 是没报错

工具开启了白名单屏蔽混淆mipmap下所有和id,还是爆：
这个地方。
try {
    return mAssets.openNonAssetFd(
        value.assetCookie, value.string.toString());
} catch (Exception e) {
    NotFoundException rnf = new NotFoundException(
        "File " + value.string.toString()
        + " from drawable resource ID #0x"
        + Integer.toHexString(id));
    rnf.initCause(e);
    throw rnf;
} finally {
    synchronized (mAccessLock) {
        if (mTmpValue == null) {
            mTmpValue = value;
        }
    }
}




from @1024iCloud

**Comment by simpleton** [comment]
@1024iCloud 你现在还存在问题么？
我试了下umeng share sdk的example，正确添加白名单后是可以work的。umeng_share_sdk使用了一套自己加载资源的方法，所以会出现这种情况。

**Comment by 1024iCloud** [comment]
@simpleton 这个我替换成url了,版本我的是1.1.9哦:smile:
