### ISSUE TITLE
resource_mapping_xxx.txt是原始与混淆后代码间的映射吗?

### ISSUE THREAD

**Issue by JakeWoki** [shwenzhang/AndResGuard#94]
[图片](https://github.com/JakeWoki/android-open-project/blob/master/QQ%E5%9B%BE%E7%89%8720160926145310.png?raw=true)
看了里面的东西，怎么感觉没有对类，方法和字段名进行混淆呢？@simpleton

**Comment by simpleton** [comment]
这个repo只是混淆资源。类、方法可以用Proguard。

**Comment by JakeWoki** [comment]
@simpleton 能具体说一下是怎么操作的吗？

**Comment by simpleton** [comment]
具体使用方法可以参照readme。

**Comment by JakeWoki** [comment]
readme是eclipse的使用方法吧，as怎么用？

**Comment by simpleton** [comment]
请再读一遍readme，AndResGuard-example
<https://github.com/shwenzhang/AndResGuard/tree/master/AndResGuard-example>
 下有一个简单例子也可以参考。

**Comment by JakeWoki** [comment]
还是不明白::>_<::

**Comment by magenchen** [comment]
运行andresguard/resguard的gradle任务，可以得到资源混淆的安装包 
命令行可直接运行./gradlew resguard
这句话的意思是可以通过两种方式得到资源混淆的安装包么？
![image](https://cloud.githubusercontent.com/assets/5335426/18943679/b10406be-8653-11e6-9ebf-98cbceef69cb.png)
gradle任务  是app中那个tasks>abdresguard>resguard任务么？

**Comment by simpleton** [comment]
@magenchen 是的。这个task是依赖assembleRelease的，为了改变所有默认task的行为，andresguard就增加了这个task。

**Comment by JakeWoki** [comment]
![image](https://raw.githubusercontent.com/JakeWoki/android-open-project/master/QQ%E6%88%AA%E5%9B%BE20160929151814.png)
这样是成功了吗？

**Comment by simpleton** [comment]
@JakeWoki 是的。我稍后更新下readme，做一些更详细的说明。
