### ISSUE TITLE
项目中使用gradle出现的提示

### ISSUE THREAD

**Issue by magenchen** [shwenzhang/AndResGuard#95]
如图，讲gradle配置引入，sync now编译的时候，出现了如下问题：
![image](https://cloud.githubusercontent.com/assets/5335426/18948776/084cf234-866b-11e6-99e4-41e3b3d92126.png)
而且 没能在task中找到AndResGuard任务，请问是为什么。该如何解决？

**Comment by simpleton** [comment]
请确认是否开启了offline？

**Comment by magenchen** [comment]
好像是没找到这两个文件的意思。gradle一直配置的都是offline模式。
是否在配置了gradle之后，还需要下载这两个文件？

**Comment by simpleton** [comment]
关掉offline，同步好之后再打开offline.

**Comment by magenchen** [comment]
![image](https://cloud.githubusercontent.com/assets/5335426/19209517/50a34a9a-8d3e-11e6-9490-03dd6b53c369.png)
如上图，gradle配置。并且关闭了offline。
![image](https://cloud.githubusercontent.com/assets/5335426/19209523/7a3c1e68-8d3e-11e6-8433-b308572252ba.png)
还是出现了以上问题。求助

**Comment by simpleton** [comment]
@magenchen 请添加jcenter源于buildscript中
```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.tencent.mm:AndResGuard-gradle-plugin:1.1.11'
    }
}
```
