### ISSUE TITLE
关于执行java -jar andresGuard.java 包如下错请帮忙

### ISSUE THREAD

**Issue by 15189611** [shwenzhang/AndResGuard#96]
![image](https://cloud.githubusercontent.com/assets/13620658/18955788/77ac7c6a-868b-11e6-9d92-098fbaef4985.png)

**Comment by 15189611** [comment]
请问这是什么情况

**Comment by simpleton** [comment]
@15189611 因为这个jar包是我用jdk8打出来的，但你的runtime版本比我低导致的。你可以升级jre的版本，或者运行`./gradlew :AndResGuard-cli:buildJar`自己打出新包。
