### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Modify24x7** [shwenzhang/AndResGuard#99]
Hi , 
good tool, can you modify src and add new feature move every res (not folder) file to out of folder.
example :
res/layout/main.xml to a.xml
Thanks

**Comment by simpleton** [comment]
Good point, it will make resource path extreme short, but it will destroy
original folder struct that I didn't it works for android. I'll try it and
consider add experience flag in next release. And also welcome PR.

**Comment by Modify24x7** [comment]
hi, today my work complete, i'm add new feature every res file move to out off folder etc.
